(()=>{
const HN=new Set((window.HINATA_WORLD||[]).map(x=>x[0]));
const baseBegin=window.beginGame, baseRender=window.render, baseEnd=window.endMonth;
function imgFor(name){const src=window.HINATA_PORTRAITS&&window.HINATA_PORTRAITS[name];return src?`<img class="portrait-face" src="${src}" alt="${name}">`:`<span class="face">${name[0]}</span>`}
function enhance(){document.querySelectorAll('.officer').forEach(el=>{const name=el.querySelector('b')?.textContent?.trim();if(name&&window.HINATA_PORTRAITS?.[name]){const old=el.querySelector('.face,.portrait-face');if(old)old.outerHTML=imgFor(name)}});document.querySelectorAll('.toast').forEach(el=>{const name=el.querySelector('b')?.textContent?.trim();if(name&&window.HINATA_PORTRAITS?.[name]){const old=el.querySelector('.face,.portrait-face');if(old)old.outerHTML=imgFor(name)}})}
window.render=function(){baseRender();setTimeout(enhance,0)};
window.beginGame=function(){baseBegin();state.version=1.2;state.officers.forEach(o=>{if(HN.has(o.name)){o.discovered=false;if(o.force==='在野')o.status='潜伏'}});['佐々木久美','加藤史帆','齊藤京子','井口眞緒'].forEach(n=>{const o=state.officers.find(x=>x.name===n);if(o)o.discovered=true});log('各地の日向坂武将の所在は不明。捜索や風聞で発見できる。');render()};
window.search=function(o){const c=cityObj();if(c.gold<60)return alert('金不足');c.gold-=60;const local=state.officers.filter(x=>HN.has(x.name)&&!x.discovered&&x.city===state.selected);const rumor=state.officers.filter(x=>HN.has(x.name)&&!x.discovered&&x.force!=='在野');const roll=Math.random()*100;if(local.length&&roll<38+o.int*.55){const t=local[Math.floor(Math.random()*local.length)];t.discovered=true;t.status=t.force==='在野'?'在野':'一般';finish(o,`${t.name}を${state.selected}で発見しました。`)}else if(rumor.length&&roll<58+o.int*.38){const t=rumor[Math.floor(Math.random()*rumor.length)];t.discovered=true;finish(o,`風聞により、${t.name}が${t.force}軍の${t.city}にいると判明しました。`)}else{const g=rnd(40,150);c.gold+=g;finish(o,`人材は見つかりませんでしたが、金${g}を発見しました。`)}};
window.hire=function(o){const ts=state.officers.filter(x=>{if(HN.has(x.name)&&!x.discovered)return false;if(x.status==='君主'||x.force==='日向軍')return false;return(x.force==='在野'&&x.city===state.selected)||(HN.has(x.name)&&x.force&&x.force!=='在野')});if(!ts.length)return alert('登用できることが判明している人物はいません。まず捜索してください。');showModal(`<h2>登用</h2><div class="choice-list">${ts.slice(0,30).map(t=>`<button data-target="${t.name}"><b>${t.name}</b> ${t.force} ${t.city} 忠${t.loy}</button>`).join('')}</div><button data-close>閉じる</button>`);modalCard.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{const t=state.officers.find(x=>x.name===b.dataset.target),chance=Math.min(90,15+o.cha*.45+(100-t.loy)*.45-(t.force==='在野'?0:20));cityObj().gold-=Math.min(180,cityObj().gold);const ok=Math.random()*100<chance;closeModal();if(ok){t.force='日向軍';t.city=state.selected;t.status='一般';t.loy=70;t.discovered=true;finish(o,`${t.name}の登用に成功しました。`)}else finish(o,`${t.name}の登用に失敗しました。`)})};
window.endMonth=function(){if(state){const hidden=state.officers.filter(x=>HN.has(x.name)&&!x.discovered&&x.force==='在野'),enemyForces=Object.keys(FORCES);hidden.forEach(t=>{if(Math.random()<.08){const f=enemyForces[Math.floor(Math.random()*enemyForces.length)],city=Object.keys(state.cities).find(n=>state.cities[n].force===f);if(city){t.force=f;t.city=city;t.status='一般';t.loy=rnd(62,86)}}})}baseEnd()};
const style=document.createElement('style');style.textContent='.portrait-face{width:46px;height:46px;border-radius:9px;object-fit:cover;border:1px solid #b9904c;flex:0 0 46px}.toast .portrait-face{width:58px;height:58px;border-radius:50%}';document.head.appendChild(style);setTimeout(enhance,300);
})();