(function(global){
'use strict';
global.HinataEvents=[
{id:'ig1',member:'ig',bond:1,title:'帰り道の反省会',text:'次のMC案を一緒に考えた。',stats:{3:3,0:1}},
{id:'ig3',member:'ig',bond:3,title:'アドリブ特訓',text:'即興企画を最後まで走り切った。',stats:{3:5},staff:2},
{id:'ush1',member:'ush',bond:1,title:'小さなしおり',text:'少しだけ肩の力が抜けた。',energy:12},
{id:'ush3',member:'ush',bond:3,title:'みんなをつなぐ言葉',text:'楽屋の空気がやわらいだ。',stats:{4:3},staff:3},
{id:'mem1',member:'mem',bond:1,title:'鏡の前の表情',text:'曲の主人公の気持ちを考えた。',stats:{4:4}},
{id:'mem3',member:'mem',bond:3,title:'本番前の約束',text:'小さな約束が表情を変えた。',stats:{4:5,0:2}},
{id:'kat1',member:'kat',bond:1,title:'居残り練習',text:'もう一度だけ振りを合わせた。',stats:{2:3,0:1}},
{id:'kat3',member:'kat',bond:3,title:'全力の背中',text:'最後まで一緒に踊った。',stats:{2:5},staff:2},
{id:'kyo1',member:'kyo',bond:1,title:'歌の自主練',text:'同じフレーズを何度も歌った。',stats:{1:4}},
{id:'kyo3',member:'kyo',bond:3,title:'二人のハーモニー',text:'声が重なり、空気が変わった。',stats:{1:6,0:2}},
{id:'kum1',member:'kum',bond:1,title:'練習メモ',text:'全員の動きを整理した。',staff:4},
{id:'kum3',member:'kum',bond:3,title:'円陣の中心',text:'全員の気持ちが一つになった。',staff:5,allBond:1},
{id:'mir1',member:'mir',bond:1,title:'楽屋の差し入れ',text:'疲れた楽屋に笑顔が戻った。',energy:15},
{id:'mir3',member:'mir',bond:3,title:'ライブの景色',text:'ステージの端まで走った。',stats:{0:4,2:3}},
{id:'tak1',member:'tak',bond:1,title:'映像分析会',text:'審査員の視線を読み解いた。',staff:3},
{id:'tak3',member:'tak',bond:3,title:'選抜対策ノート',text:'次の審査への道筋が見えた。',examBonus:5},
{id:'aya1',member:'aya',bond:1,title:'衣装合わせ',text:'立ち姿を整えた。',stats:{4:4}},
{id:'aya3',member:'aya',bond:3,title:'歩幅をそろえて',text:'写真の印象が変わった。',stats:{4:5,0:2}},
{id:'mei1',member:'mei',bond:1,title:'ダンス練習',text:'何度も踊り、呼吸がそろった。',stats:{2:4}},
{id:'mei3',member:'mei',bond:3,title:'フォーメーション完成',text:'難しい移動を完成させた。',stats:{2:6}},
{id:'pair1',members:['kat','kyo'],bond:3,title:'ライバル同士の自主練',text:'歌もダンスも限界まで磨かれた。',stats:{1:4,2:4,0:2}},
{id:'pair2',members:['aya','mei'],bond:3,title:'放課後の練習',text:'自然な笑顔が増えた。',stats:{2:3,4:3,0:3}},
{id:'pair3',members:['kum','mir'],bond:3,title:'楽屋を照らす二人',text:'全員が再び前を向いた。',staff:5,allBond:1},
{id:'all1',averageBond:2,title:'一期生の円陣',text:'その輪の中に自分もいた。',stats:{0:3},staff:3},
{id:'all2',averageBond:3.5,title:'大切なライブの夜',text:'忘れられない景色になった。',stats:{0:6,1:2,2:2,3:2,4:2},staff:5}
];
})(window);