(function(){
'use strict';
var canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),msg=document.getElementById('message'),status=document.getElementById('status'),commands=document.getElementById('commands');
var TILE=32,COLS=15,ROWS=12;
var state=JSON.parse(localStorage.getItem('hinata_quest_v01')||'null')||{map:'town',x:7,y:9,dir:'up',steps:0,hero:{name:'あなた',lv:1,hp:28,maxHp:28,mp:8,maxMp:8,atk:8,def:5,exp:0,gold:20},party:['佐々木久美'],flags:{intro:false,kyo:false,boss:false}};
var mode='map',battle=null;
var maps={
 town:{name:'はじまりの王都',tiles:[
'###############','#.....#.......#','#..H..#..H....#','#.....#.......#','#.............#','#..N......N...#','#.............#','#.....##......#','#.............#','#......P......#','#......G......#','###############'],npcs:[{x:3,y:5,name:'佐々木久美',text:['久美「どうやら私たち、RPGの世界に転生したみたい。」','久美「まずは町の南から草原へ出て、京子を探そう！」']},{x:10,y:5,name:'潮紗理菜',text:['潮「傷ついたら町へ戻ってきてね。」','潮「祈りの力で、みんなのHPとMPを回復します。」'],heal:true}],warps:[{x:7,y:10,to:'field',tx:7,ty:1}]},
 field:{name:'ひなた草原',tiles:[
'###############','#......P......#','#..^^.....^^..#','#.............#','#....~~~~.....#','#....~~~~..N..#','#.............#','#..^^.....^^..#','#.............#','#.....B.......#','#.............#','###############'],npcs:[{x:10,y:5,name:'齊藤京子',text:['京子「やっと見つけた。ここ、魔物が普通に出るんだけど。」','京子「一緒に行く。私の歌魔法、意外と強いよ。」'],join:'齊藤京子'}],warps:[{x:7,y:1,to:'town',tx:7,ty:9}],encounter:true,boss:{x:6,y:9,name:'闇のマネージャー',hp:55,atk:10,def:4,exp:35,gold:40}}
};
function save(){localStorage.setItem('hinata_quest_v01',JSON.stringify(state));}
function tileAt(map,x,y){return maps[map].tiles[y]&&maps[map].tiles[y][x];}
function blocked(ch){return ch==='#'||ch==='~'||ch==='H'||ch==='N'||ch==='B';}
function render(){drawMap();drawStatus();}
function drawMap(){var m=maps[state.map];ctx.clearRect(0,0,canvas.width,canvas.height);for(var y=0;y<ROWS;y++)for(var x=0;x<COLS;x++){var ch=m.tiles[y][x],c='#6b7280';if(ch==='.')c='#71b85f';if(ch==='#')c='#31523b';if(ch==='~')c='#3b82f6';if(ch==='^')c='#4b7f52';if(ch==='H')c='#b45309';if(ch==='G')c='#d1d5db';ctx.fillStyle=c;ctx.fillRect(x*TILE,y*TILE,TILE,TILE);ctx.strokeStyle='#0002';ctx.strokeRect(x*TILE,y*TILE,TILE,TILE);if(ch==='H'){ctx.fillStyle='#7c2d12';ctx.fillRect(x*TILE+5,y*TILE+9,22,18);ctx.fillStyle='#fef3c7';ctx.fillRect(x*TILE+12,y*TILE+17,7,10)}if(ch==='^'){ctx.fillStyle='#194d2e';ctx.beginPath();ctx.moveTo(x*TILE+16,y*TILE+4);ctx.lineTo(x*TILE+5,y*TILE+26);ctx.lineTo(x*TILE+27,y*TILE+26);ctx.fill()}if(ch==='B'){ctx.fillStyle='#111827';ctx.fillRect(x*TILE+7,y*TILE+7,18,18);ctx.fillStyle='#ef4444';ctx.fillRect(x*TILE+11,y*TILE+11,4,4);ctx.fillRect(x*TILE+18,y*TILE+11,4,4)}}m.npcs.forEach(function(n){ctx.fillStyle=n.name.indexOf('京子')>=0?'#9333ea':n.name.indexOf('潮')>=0?'#0ea5e9':'#f59e0b';ctx.fillRect(n.x*TILE+8,n.y*TILE+6,16,22);ctx.fillStyle='#fff';ctx.fillRect(n.x*TILE+11,n.y*TILE+9,3,3);ctx.fillRect(n.x*TILE+18,n.y*TILE+9,3,3)});ctx.fillStyle='#f8fafc';ctx.fillRect(state.x*TILE+8,state.y*TILE+5,16,23);ctx.fillStyle='#111827';ctx.fillRect(state.x*TILE+11,state.y*TILE+9,3,3);ctx.fillRect(state.x*TILE+18,state.y*TILE+9,3,3);ctx.fillStyle='#000';ctx.font='12px monospace';ctx.fillText(m.name,8,16)}
function drawStatus(){var h=state.hero;status.innerHTML='<div class="stat">Lv '+h.lv+'</div><div class="stat">HP '+h.hp+'/'+h.maxHp+'</div><div class="stat">MP '+h.mp+'/'+h.maxMp+'</div><div class="stat">'+h.gold+' G</div><div class="stat" style="grid-column:1/-1">仲間：'+state.party.join('・')+'</div>';}
function say(lines,done){mode='dialog';var i=0;msg.textContent=lines[i];commands.classList.add('hidden');function next(){i++;if(i<lines.length){msg.textContent=lines[i];}else{mode='map';msg.textContent=maps[state.map].name+'を冒険中。';document.removeEventListener('hinataNext',next);if(done)done();render();}}document.addEventListener('hinataNext',next);}
function action(){if(mode==='dialog'){document.dispatchEvent(new Event('hinataNext'));return}if(mode==='battle'){return}var dx=0,dy=0;if(state.dir==='up')dy=-1;if(state.dir==='down')dy=1;if(state.dir==='left')dx=-1;if(state.dir==='right')dx=1;var tx=state.x+dx,ty=state.y+dy,m=maps[state.map];var npc=m.npcs.find(function(n){return n.x===tx&&n.y===ty});if(npc){say(npc.text,function(){if(npc.heal){state.hero.hp=state.hero.maxHp;state.hero.mp=state.hero.maxMp;msg.textContent='潮の祈りで全回復した。';save()}if(npc.join&&!state.flags.kyo){state.flags.kyo=true;state.party.push(npc.join);msg.textContent=npc.join+'が仲間になった！';save()}});return}if(m.boss&&!state.flags.boss&&m.boss.x===tx&&m.boss.y===ty){startBattle(m.boss,true);return}msg.textContent='そこには特に何もない。';}
function move(dir){if(mode!=='map')return;state.dir=dir;var dx=dir==='left'?-1:dir==='right'?1:0,dy=dir==='up'?-1:dir==='down'?1:0,nx=state.x+dx,ny=state.y+dy,ch=tileAt(state.map,nx,ny);if(!blocked(ch)){state.x=nx;state.y=ny;state.steps++;var warp=maps[state.map].warps.find(function(w){return w.x===nx&&w.y===ny});if(warp){state.map=warp.to;state.x=warp.tx;state.y=warp.ty;msg.textContent=maps[state.map].name+'へ来た。'}else if(maps[state.map].encounter&&state.steps>3&&Math.random()<0.18){state.steps=0;startBattle(randomEnemy(),false);save();return}save()}render()}
function randomEnemy(){var a=[{name:'ひなたスライム',hp:18,atk:6,def:2,exp:8,gold:5},{name:'迷子のゴーレム',hp:26,atk:8,def:4,exp:13,gold:9},{name:'黒いコウモリ',hp:20,atk:7,def:2,exp:10,gold:7}];return JSON.parse(JSON.stringify(a[Math.floor(Math.random()*a.length)]))}
function startBattle(enemy,boss){mode='battle';battle={enemy:JSON.parse(JSON.stringify(enemy)),boss:boss};msg.textContent=enemy.name+'が あらわれた！';showBattleMenu();render()}
function showBattleMenu(){commands.classList.remove('hidden');commands.innerHTML='<button data-cmd="attack">たたかう</button><button data-cmd="spell">うたまほう</button><button data-cmd="heal">やくそう</button><button data-cmd="run">にげる</button>';}
function battleCommand(cmd){if(mode!=='battle')return;var h=state.hero,e=battle.enemy;if(cmd==='attack'){var d=Math.max(1,h.atk+Math.floor(Math.random()*5)-e.def);e.hp-=d;msg.textContent=h.name+'の攻撃！ '+e.name+'に'+d+'のダメージ。'}else if(cmd==='spell'){if(h.mp<3){msg.textContent='MPが足りない。';return}h.mp-=3;var sd=state.flags.kyo?14+Math.floor(Math.random()*8):9+Math.floor(Math.random()*5);e.hp-=sd;msg.textContent='京子の歌魔法！ '+e.name+'に'+sd+'のダメージ。'}else if(cmd==='heal'){var heal=10+Math.floor(Math.random()*7);h.hp=Math.min(h.maxHp,h.hp+heal);msg.textContent='やくそうでHPが'+heal+'回復した。'}else if(cmd==='run'){if(!battle.boss&&Math.random()<0.7){endBattle('うまく逃げ切った。');return}else msg.textContent='しかし回りこまれてしまった！'}if(e.hp<=0){winBattle();return}setTimeout(enemyTurn,450);drawStatus()}
function enemyTurn(){if(mode!=='battle')return;var h=state.hero,e=battle.enemy,d=Math.max(1,e.atk+Math.floor(Math.random()*4)-h.def);h.hp-=d;msg.textContent=e.name+'の攻撃！ '+h.name+'は'+d+'のダメージ。';if(h.hp<=0){h.hp=h.maxHp;h.mp=h.maxMp;h.gold=Math.max(0,h.gold-10);state.map='town';state.x=7;state.y=9;endBattle('目の前が真っ暗になった……。潮に助けられ、王都へ戻った。')}save();drawStatus()}
function winBattle(){var h=state.hero,e=battle.enemy;h.exp+=e.exp;h.gold+=e.gold;var text=e.name+'を倒した！ '+e.exp+'EXPと'+e.gold+'Gを獲得。';if(battle.boss){state.flags.boss=true;text+=' 草原に平和が戻った！'}while(h.exp>=h.lv*20){h.exp-=h.lv*20;h.lv++;h.maxHp+=6;h.maxMp+=2;h.atk+=2;h.def+=1;h.hp=h.maxHp;h.mp=h.maxMp;text+=' レベルが'+h.lv+'に上がった！'}endBattle(text)}
function endBattle(text){mode='map';battle=null;commands.classList.add('hidden');msg.textContent=text;save();render()}
document.addEventListener('keydown',function(e){if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' '].indexOf(e.key)>=0)e.preventDefault();if(e.key==='ArrowUp')move('up');if(e.key==='ArrowDown')move('down');if(e.key==='ArrowLeft')move('left');if(e.key==='ArrowRight')move('right');if(e.key==='Enter'||e.key===' ')action()});
document.addEventListener('click',function(e){var k=e.target.getAttribute('data-key'),c=e.target.getAttribute('data-cmd');if(k){if(k==='action')action();else move(k)}if(c)battleCommand(c)});
if(!state.flags.intro){state.flags.intro=true;say(['ライブ本番直前、まばゆい光がメンバーたちを包んだ。','目を開けると、そこは剣と魔法の世界だった。','久美「とにかく、みんなを探して元の世界へ帰ろう！」'],save)}else msg.textContent=maps[state.map].name+'を冒険中。';render();
})();