(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),msg=document.getElementById('message'),status=document.getElementById('status'),commands=document.getElementById('commands');
const TILE=32,COLS=15,ROWS=12,SAVE='hinata_quest_v02';
const fresh=()=>({map:'town',x:7,y:9,dir:'up',steps:0,hero:{lv:1,hp:32,maxHp:32,mp:10,maxMp:10,atk:8,def:5,exp:0,next:20,gold:35,weapon:'木のペンライト',armor:'旅の衣',herbs:2},party:['佐々木久美'],flags:{kyo:false,katoshi:false,mirei:false,fieldBoss:false,forestBoss:false,caveBoss:false,clear:false},chests:{}});
let state=load(),mode='map',battle=null,dialogDone=null;
const maps={
 town:{name:'はじまりの王都',tiles:['###############','#..H..#..H....#','#.....#.......#','#.............#','#..S......I...#','#.............#','#..N......N...#','#.............#','#.............#','#......P......#','#......G......#','###############'],npcs:[{x:3,y:6,name:'佐々木久美',text:['久美「異世界でもキャプテンはキャプテンです。」','久美「南の草原で京子を探そう！」']},{x:10,y:6,name:'潮紗理菜',text:['潮「傷ついたら、いつでも戻ってきてね。」'],heal:true},{x:3,y:4,name:'武器屋',shop:'weapon'},{x:10,y:4,name:'宿屋',inn:true}],warps:[{x:7,y:10,to:'field',tx:7,ty:1}]},
 field:{name:'ひなた草原',tiles:['###############','#......P......#','#..^^.....^^..#','#.............#','#....~~~~.....#','#....~~~~..N..#','#.............#','#..^^.....^^..#','#.............#','#.....B....C..#','#......G......#','###############'],npcs:[{x:10,y:5,name:'齊藤京子',text:['京子「やっと来た。魔物、思ったより強いよ。」','京子「一緒に行く。歌魔法で吹き飛ばすから。」'],join:'齊藤京子',flag:'kyo'}],warps:[{x:7,y:1,to:'town',tx:7,ty:9},{x:7,y:10,to:'forest',tx:7,ty:1}],encounters:['ひなたスライム','わらいキノコ'],boss:{x:6,y:9,name:'闇のマネージャー',hp:70,atk:11,def:4,exp:45,gold:50,flag:'fieldBoss'},chests:[{x:11,y:9,id:'field1',gold:40}]},
 forest:{name:'こさかなの森',tiles:['###############','#......P......#','#.^^^^...^^^^.#','#...#.....#...#','#...#..N..#...#','#.............#','#.^^..###..^^.#','#.............#','#..C......B...#','#.............#','#......G......#','###############'],npcs:[{x:7,y:4,name:'加藤史帆',text:['史帆「森で迷ってたら、すごく強そうな敵がいた。」','史帆「守るのは得意。仲間に入れて！」'],join:'加藤史帆',flag:'katoshi'}],warps:[{x:7,y:1,to:'field',tx:7,ty:9},{x:7,y:10,to:'cave',tx:7,ty:1}],encounters:['森のモコモコ','いたずらバット'],boss:{x:10,y:8,name:'影の騎士',hp:115,atk:15,def:7,exp:85,gold:90,flag:'forestBoss'},chests:[{x:3,y:8,id:'forest1',item:'herb',amount:3}]},
 cave:{name:'月星の洞窟',tiles:['###############','#......P......#','#.###.....###.#','#.....#.#.....#','#..C..#.#..N..#','#.....#.#.....#','#.............#','#.###.....###.#','#.....B.......#','#.............#','#......G......#','###############'],npcs:[{x:11,y:4,name:'佐々木美玲',text:['美玲「洞窟の奥に、元の世界へ戻る鍵があるみたい。」','美玲「パンはないけど、私も一緒に戦う！」'],join:'佐々木美玲',flag:'mirei'}],warps:[{x:7,y:1,to:'forest',tx:7,ty:9},{x:7,y:10,to:'ending',tx:7,ty:9,need:'caveBoss'}],encounters:['月影ゴーレム','洞窟ドラキー'],boss:{x:6,y:8,name:'魔王ノクターン',hp:190,atk:20,def:10,exp:180,gold:200,flag:'caveBoss'},chests:[{x:3,y:4,id:'cave1',weapon:'聖なるマイク',atk:7}]},
 ending:{name:'光のステージ',tiles:['###############','#.............#','#.............#','#....*****....#','#...*******...#','#..*********..#','#...*******...#','#....*****....#','#.............#','#......P......#','#.............#','###############'],npcs:[],warps:[]}
};
const enemies={
 'ひなたスライム':{hp:22,atk:7,def:2,exp:10,gold:8},'わらいキノコ':{hp:28,atk:8,def:3,exp:13,gold:10},
 '森のモコモコ':{hp:38,atk:11,def:5,exp:19,gold:16},'いたずらバット':{hp:32,atk:13,def:3,exp:21,gold:18},
 '月影ゴーレム':{hp:58,atk:17,def:8,exp:32,gold:28},'洞窟ドラキー':{hp:45,atk:18,def:5,exp:30,gold:25}
};
function load(){try{return JSON.parse(localStorage.getItem(SAVE))||fresh()}catch(e){return fresh()}}
function save(text){localStorage.setItem(SAVE,JSON.stringify(state));if(text)msg.textContent=text}
function tileAt(x,y){return maps[state.map].tiles[y]?.[x]||'#'}
function blocked(ch){return '#~H^'.includes(ch)}
function npcAt(x,y){return maps[state.map].npcs.find(n=>n.x===x&&n.y===y)}
function chestAt(x,y){return (maps[state.map].chests||[]).find(c=>c.x===x&&c.y===y)}
function render(){drawMap();drawStatus()}
function drawMap(){const m=maps[state.map];ctx.clearRect(0,0,480,384);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const ch=m.tiles[y][x];let c=ch==='#'?'#263c35':ch==='~'?'#3578c9':state.map==='cave'?'#514a64':state.map==='ending'?'#211b3e':'#70b45c';ctx.fillStyle=c;ctx.fillRect(x*TILE,y*TILE,TILE,TILE);ctx.strokeStyle='#0002';ctx.strokeRect(x*TILE,y*TILE,TILE,TILE);if(ch==='^'){ctx.fillStyle='#174d2c';ctx.beginPath();ctx.moveTo(x*TILE+16,y*TILE+3);ctx.lineTo(x*TILE+4,y*TILE+27);ctx.lineTo(x*TILE+28,y*TILE+27);ctx.fill()}if(ch==='H'){ctx.fillStyle='#8b4513';ctx.fillRect(x*TILE+5,y*TILE+10,22,17);ctx.fillStyle='#f5df9a';ctx.fillRect(x*TILE+12,y*TILE+18,7,9)}if(ch==='S'||ch==='I'){ctx.fillStyle=ch==='S'?'#eab308':'#22c55e';ctx.fillRect(x*TILE+6,y*TILE+6,20,20)}if(ch==='C'&&!state.chests[(chestAt(x,y)||{}).id]){ctx.fillStyle='#9a5b24';ctx.fillRect(x*TILE+6,y*TILE+10,20,15);ctx.fillStyle='#fbbf24';ctx.fillRect(x*TILE+14,y*TILE+13,4,7)}if(ch==='B'){ctx.fillStyle='#171421';ctx.fillRect(x*TILE+6,y*TILE+5,20,23);ctx.fillStyle='#ef4444';ctx.fillRect(x*TILE+11,y*TILE+11,3,3);ctx.fillRect(x*TILE+18,y*TILE+11,3,3)}if(ch==='*'){ctx.fillStyle='#fde68a';ctx.fillRect(x*TILE+13,y*TILE+13,6,6)}}
 m.npcs.forEach(n=>{if(n.join&&state.flags[n.flag])return;ctx.fillStyle=n.name.includes('京子')?'#9333ea':n.name.includes('史帆')?'#ec4899':n.name.includes('美玲')?'#f59e0b':n.name.includes('潮')?'#0ea5e9':'#eab308';ctx.fillRect(n.x*TILE+8,n.y*TILE+6,16,22)});
 ctx.fillStyle='#f8fafc';ctx.fillRect(state.x*TILE+8,state.y*TILE+5,16,23);ctx.fillStyle='#111827';ctx.fillRect(state.x*TILE+11,state.y*TILE+9,3,3);ctx.fillRect(state.x*TILE+18,state.y*TILE+9,3,3);ctx.fillStyle='#fff';ctx.font='bold 12px monospace';ctx.fillText(m.name,8,16)}
function drawStatus(){const h=state.hero;status.innerHTML=`<div class="stat">Lv ${h.lv}</div><div class="stat">HP ${h.hp}/${h.maxHp}</div><div class="stat">MP ${h.mp}/${h.maxMp}</div><div class="stat">${h.gold} G</div><div class="stat wide">仲間：${state.party.join('・')}　武器：${h.weapon}　薬草：${h.herbs}</div>`}
function setCommands(items){commands.innerHTML='';commands.classList.remove('hidden');items.forEach(i=>{const b=document.createElement('button');b.textContent=i.label;b.disabled=!!i.disabled;b.onclick=i.fn;commands.appendChild(b)})}
function clearCommands(){commands.classList.add('hidden');commands.innerHTML=''}
function say(lines,done){mode='dialog';let i=0;msg.textContent=lines[i];dialogDone=()=>{i++;if(i<lines.length){msg.textContent=lines[i]}else{mode='map';dialogDone=null;done?.();clearCommands();render()}}}
function move(dx,dy,dir){if(mode!=='map')return;state.dir=dir;const nx=state.x+dx,ny=state.y+dy,m=maps[state.map],n=npcAt(nx,ny),boss=m.boss;if(n&&!(n.join&&state.flags[n.flag])){render();return}if(boss&&!state.flags[boss.flag]&&boss.x===nx&&boss.y===ny){render();return}if(chestAt(nx,ny)&&!state.chests[chestAt(nx,ny).id]){render();return}if(blocked(tileAt(nx,ny)))return;state.x=nx;state.y=ny;state.steps++;const w=m.warps.find(w=>w.x===nx&&w.y===ny);if(w){if(w.need&&!state.flags[w.need]){msg.textContent='まだ先へ進めない。';return}state.map=w.to;state.x=w.tx;state.y=w.ty;msg.textContent=maps[state.map].name+'へ来た。';if(state.map==='ending'&&!state.flags.clear)ending()}else if(m.encounters&&Math.random()<.13)startBattle(random(m.encounters),false);save();render()}
function action(){if(mode==='dialog'){dialogDone?.();return}if(mode==='battle'||mode==='shop'||mode==='menu')return;const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[state.dir],tx=state.x+d[0],ty=state.y+d[1],m=maps[state.map],n=npcAt(tx,ty),c=chestAt(tx,ty),b=m.boss;if(n&&!(n.join&&state.flags[n.flag]))return interact(n);if(c&&!state.chests[c.id])return openChest(c);if(b&&!state.flags[b.flag]&&b.x===tx&&b.y===ty)return startBattle(b,true);msg.textContent='そこには特に何もない。'}
function interact(n){if(n.shop)return shop();if(n.inn){if(state.hero.gold<10)return say(['宿屋「10Gだけど、お金が足りないよ。」']);state.hero.gold-=10;state.hero.hp=state.hero.maxHp;state.hero.mp=state.hero.maxMp;save();return say(['宿屋「ゆっくり休んでいってね。」','HPとMPが全回復した！'])}say(n.text,()=>{if(n.heal){state.hero.hp=state.hero.maxHp;state.hero.mp=state.hero.maxMp;msg.textContent='潮の祈りで全回復した。'}if(n.join&&!state.flags[n.flag]){state.flags[n.flag]=true;state.party.push(n.join);msg.textContent=n.join+'が仲間になった！'}save()})}
function openChest(c){state.chests[c.id]=true;if(c.gold){state.hero.gold+=c.gold;msg.textContent=`宝箱から${c.gold}Gを手に入れた！`}if(c.item==='herb'){state.hero.herbs+=c.amount;msg.textContent=`薬草を${c.amount}個手に入れた！`}if(c.weapon){state.hero.weapon=c.weapon;state.hero.atk+=c.atk;msg.textContent=`${c.weapon}を手に入れ、装備した！ 攻撃力+${c.atk}`}save();render()}
function shop(){mode='shop';msg.textContent='武器屋「何を買う？」';const goods=[['銅のペンライト',50,3],['銀のマイク',120,6],['薬草',12,0]];setCommands(goods.map(g=>({label:`${g[0]} ${g[1]}G`,disabled:state.hero.gold<g[1],fn:()=>{state.hero.gold-=g[1];if(g[0]==='薬草')state.hero.herbs++;else{state.hero.weapon=g[0];state.hero.atk=8+g[2]+(state.hero.lv-1)*2}save();msg.textContent=`${g[0]}を買った！`;shop()}})).concat({label:'やめる',fn:()=>{mode='map';clearCommands();msg.textContent='またどうぞ。';render()}}))}
function random(a){return a[Math.floor(Math.random()*a.length)]}
function startBattle(enemy,isBoss){const src=typeof enemy==='string'?{name:enemy,...enemies[enemy]}:enemy;battle={...src,maxHp:src.hp,isBoss};mode='battle';msg.textContent=`${battle.name}が現れた！`;battleMenu();render()}
function battleMenu(){setCommands([{label:'たたかう',fn:()=>playerAttack(false)},{label:'うたまほう MP3',disabled:state.hero.mp<3,fn:()=>playerAttack(true)},{label:`薬草 ×${state.hero.herbs}`,disabled:state.hero.herbs<1,fn:useHerb},{label:'にげる',disabled:battle.isBoss,fn:runAway}])}
function playerAttack(magic){let dmg;if(magic){state.hero.mp-=3;dmg=Math.max(5,state.hero.atk+8+state.party.length*2-battle.def+rand(8));msg.textContent=`京子たちのうたまほう！ ${battle.name}に${dmg}のダメージ！`}else{dmg=Math.max(1,state.hero.atk+state.party.length-battle.def+rand(6));msg.textContent=`みんなの攻撃！ ${battle.name}に${dmg}のダメージ！`}battle.hp-=dmg;if(battle.hp<=0)return setTimeout(winBattle,450);setTimeout(enemyTurn,500)}
function useHerb(){state.hero.herbs--;const heal=24;state.hero.hp=Math.min(state.hero.maxHp,state.hero.hp+heal);msg.textContent=`薬草を使い、HPが${heal}回復した。`;setTimeout(enemyTurn,450)}
function runAway(){if(Math.random()<.65){mode='map';battle=null;clearCommands();msg.textContent='うまく逃げ切った！';render()}else{msg.textContent='しかし、逃げられなかった！';setTimeout(enemyTurn,450)}}
function enemyTurn(){const dmg=Math.max(1,battle.atk-state.hero.def+rand(6));state.hero.hp-=dmg;msg.textContent=`${battle.name}の攻撃！ ${dmg}のダメージ！`;if(state.hero.hp<=0)return setTimeout(defeat,550);save();setTimeout(battleMenu,500);render()}
function winBattle(){const b=battle;state.hero.exp+=b.exp;state.hero.gold+=b.gold;if(b.isBoss&&b.flag)state.flags[b.flag]=true;mode='map';battle=null;clearCommands();let t=`${b.name}を倒した！\n経験値${b.exp}、${b.gold}Gを獲得。`;while(state.hero.exp>=state.hero.next){state.hero.exp-=state.hero.next;state.hero.lv++;state.hero.next=Math.floor(state.hero.next*1.45);state.hero.maxHp+=8;state.hero.maxMp+=3;state.hero.hp=state.hero.maxHp;state.hero.mp=state.hero.maxMp;state.hero.atk+=2;state.hero.def+=2;t+=`\nレベル${state.hero.lv}になった！`}if(b.flag==='fieldBoss')t+='\n森への道が開いた。';if(b.flag==='forestBoss')t+='\n洞窟への道が開いた。';if(b.flag==='caveBoss')t+='\n光の扉が現れた。南へ進もう。';msg.textContent=t;save();render()}
function defeat(){state.hero.hp=state.hero.maxHp;state.hero.mp=state.hero.maxMp;state.hero.gold=Math.floor(state.hero.gold/2);state.map='town';state.x=7;state.y=9;mode='map';battle=null;clearCommands();msg.textContent='全滅した……。潮の祈りで王都へ戻された。所持金が半分になった。';save();render()}
function rand(n){return Math.floor(Math.random()*n)}
function menu(){if(mode!=='map')return;mode='menu';msg.textContent=`冒険の記録\nレベル ${state.hero.lv}　経験値 ${state.hero.exp}/${state.hero.next}\n攻撃 ${state.hero.atk}　守備 ${state.hero.def}\n武器 ${state.hero.weapon}\n仲間 ${state.party.join('、')}`;setCommands([{label:'全回復 30G',disabled:state.hero.gold<30,fn:()=>{state.hero.gold-=30;state.hero.hp=state.hero.maxHp;state.hero.mp=state.hero.maxMp;save();menu()}},{label:'閉じる',fn:()=>{mode='map';clearCommands();msg.textContent=maps[state.map].name+'を冒険中。';render()}}])}
function ending(){state.flags.clear=true;save();setTimeout(()=>say(['光が世界を包んだ。','久美「みんな、帰れるみたい。」','京子「でも、この冒険……忘れたくないね。」','次の瞬間、そこはライブ会場の舞台袖だった。','スタッフ「本番5分前です！」','日向坂クエスト v0.2 クリア！'],()=>{msg.textContent='クリア後も世界を歩けます。'}),300)}
document.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.key;if(k==='action')action();else if(k==='up')move(0,-1,'up');else if(k==='down')move(0,1,'down');else if(k==='left')move(-1,0,'left');else move(1,0,'right')}));
document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter',' ','m','M'].includes(e.key))e.preventDefault();if(e.key==='ArrowUp')move(0,-1,'up');if(e.key==='ArrowDown')move(0,1,'down');if(e.key==='ArrowLeft')move(-1,0,'left');if(e.key==='ArrowRight')move(1,0,'right');if(e.key==='Enter'||e.key===' ')action();if(e.key==='m'||e.key==='M')menu()});
document.getElementById('menuBtn').onclick=menu;document.getElementById('saveBtn').onclick=()=>save('冒険の書に記録した。');document.getElementById('resetBtn').onclick=()=>{if(confirm('セーブデータを消して最初から始めますか？')){state=fresh();save();location.reload()}};
if(state.map==='ending'&&!state.flags.clear)ending();else msg.textContent=maps[state.map].name+'を冒険中。';render();
})();