(() => {
'use strict';
const SAVE='hinata-senki-chapter5-direct-v1',TRIAL=new URLSearchParams(location.search).get('mode')==='trial'||localStorage.getItem('hs-trial-active-v1')==='1';
const $=s=>document.querySelector(s),K=(x,y)=>`${x},${y}`,D=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y),W=18,H=14;
const rows=['##################','#....m...S....E..#','#.ffm.m..rrr..x..#','#.V.m.m..r.xff...#','#rrrrrBrrr..ff...#','#..mm.~.S.x.m....#','#..mm.~..x..m....#','#rrrrrBrrrrrrrrrr#','#..f..~.xff..m...#','#..f..B..ff..m...#','#.....r.....m....#','#.....r..S..m....#','#C....r..........#','##################'];
const T={'#':99,'.':1,r:1,f:2,m:3,x:2,'~':99,B:1,V:1,S:1,E:1,C:1};
const WT={sword:{name:'剣',mt:6,hit:88,r:[1]},lance:{name:'槍',mt:7,hit:82,r:[1]},axe:{name:'斧',mt:8,hit:75,r:[1]},bow:{name:'弓',mt:7,hit:85,r:[2]},javelin:{name:'手槍',mt:5,hit:72,r:[1,2]},light:{name:'光',mt:5,hit:90,r:[1,2]},heal:{name:'ライブ',heal:14,r:[1],staff:true}};
const faceIds={'佐々木久美':'kumi','加藤史帆':'toshi','齊藤京子':'kyoko','井口眞緒':'mao','潮紗理菜':'sarina','河田陽菜':'hina'};
const U=(id,name,short,fac,cls,x,y,hp,str,mag,skl,spd,def,res,move,w,extra={})=>({id,name,short,faction:fac,className:cls,x,y,hp,maxHp:hp,str,mag,skl,spd,def,res,move,lv:extra.lv||7,exp:extra.exp||0,weapon:w,uses:extra.uses||30,acted:false,...extra});
function baseAllies(){return[
U('kumi','佐々木久美','久','ally','ロード',2,12,28,11,0,12,11,9,5,5,'sword',{lord:true}),U('toshi','加藤史帆','史','ally','騎兵',3,12,27,11,0,11,12,9,4,7,'lance'),U('kyoko','齊藤京子','京','ally','騎兵',4,12,26,12,0,10,11,9,4,7,'sword'),U('mao','井口眞緒','眞','ally','魔道士',5,12,22,1,10,10,9,4,8,5,'light'),U('sarina','潮紗理菜','潮','ally','シスター',2,11,23,1,11,10,9,4,10,5,'heal',{staff:true}),U('hina','河田陽菜','陽','ally','盗賊',3,11,23,8,0,13,14,6,4,6,'sword')];}
function campaignAllies(){const p=window.HinataCampaign?.loadProgressForChapter?.(5);if(!p?.units?.length)return baseAllies();const pos=[[2,12],[3,12],[4,12],[5,12],[2,11],[3,11],[4,11],[5,11]];return p.units.slice(0,8).map((u,i)=>({...u,faction:'ally',x:pos[i]?.[0]||2,y:pos[i]?.[1]||12,hp:u.maxHp||u.hp,acted:false,weapon:u.weapon||u.inventory?.[u.equippedIndex||0]?.id||'sword',uses:u.weaponUses||u.inventory?.[u.equippedIndex||0]?.uses||30}));}
function enemies(){return[
U('courier','敵伝令','令','enemy','剣士',11,7,20,8,0,12,14,5,4,5,'sword',{ai:'escape'}),U('e1','追跡兵','槍','enemy','兵士',5,11,25,10,0,9,8,8,3,4,'lance'),U('e2','追跡兵','斧','enemy','戦士',7,11,28,12,0,8,8,7,2,4,'axe'),U('e3','山弓兵','弓','enemy','弓兵',11,10,23,10,0,11,9,6,3,4,'bow'),U('e4','東道剣士','剣','enemy','剣士',14,9,25,11,0,13,13,7,4,5,'sword'),U('e5','橋守備兵','槍','enemy','兵士',9,8,27,11,0,10,9,9,3,4,'javelin'),U('e6','伏兵','斧','enemy','戦士',12,6,29,13,0,8,8,7,2,4,'axe',{sleep:true}),U('e7','伏兵','弓','enemy','弓兵',4,6,24,10,0,12,10,6,4,4,'bow',{sleep:true}),U('boss','追撃隊長','将','enemy','重装兵',15,2,37,15,0,11,7,16,7,1,'javelin',{boss:true})];}
function fresh(){return{v:1,turn:1,phase:'ally',clear:false,dispatch:false,lost:false,towers:[],flags:{},units:[...campaignAllies(),U('guest1','別働隊','援','ally','弓兵',3,3,26,10,0,13,12,7,5,6,'bow',{guest:true}),U('guest2','別働隊','援','ally','剣士',13,8,25,11,0,14,15,7,4,6,'sword',{guest:true}),...enemies()],log:['伝令を追い、分断部隊を守れ。']};}
function load(){try{const s=JSON.parse(localStorage.getItem(SAVE)||'null');if(s?.v===1)return s;}catch{}return fresh();}
let S=load(),sel=null,reach=new Map(),attack=new Set(),busy=false;
const save=()=>localStorage.setItem(SAVE,JSON.stringify(S)),by=id=>S.units.find(u=>u.id===id),at=(x,y)=>S.units.find(u=>u.hp>0&&u.x===x&&u.y===y);
function log(t){S.log.push(t);S.log=S.log.slice(-16);save();renderLog();}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1400);}
function pass(x,y,u){if(x<0||y<0||x>=W||y>=H||T[rows[y][x]]>=99)return false;const o=at(x,y);return !o||o.id===u.id||o.faction===u.faction;}
function moveRange(u){const out=new Map([[K(u.x,u.y),0]]),q=[[u.x,u.y,0]];while(q.length){const [x,y,c]=q.shift();for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy;if(!pass(nx,ny,u))continue;const n=c+T[rows[ny][nx]];if(n>u.move)continue;const k=K(nx,ny);if(out.has(k)&&out.get(k)<=n)continue;out.set(k,n);q.push([nx,ny,n]);}}return out;}
function atkFrom(x,y,u){const s=new Set(),w=WT[u.weapon]||WT.sword;for(const r of w.r)for(let dx=-r;dx<=r;dx++){const dy=r-Math.abs(dx);for(const sy of dy?[dy,-dy]:[0]){const nx=x+dx,ny=y+sy;if(nx>=0&&ny>=0&&nx<W&&ny<H)s.add(K(nx,ny));}}return s;}
function canHit(a,b){return atkFrom(a.x,a.y,a).has(K(b.x,b.y));}
function build(){const m=$('#map');m.innerHTML='';m.style.gridTemplateColumns=`repeat(${W},var(--tile))`;m.style.gridTemplateRows=`repeat(${H},var(--tile))`;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const c=document.createElement('button');c.type='button';c.className='tile';c.dataset.x=x;c.dataset.y=y;c.onclick=()=>tap(x,y);m.appendChild(c);}}
function render(){if(!$('#map .tile'))build();$('#chapterLabel').textContent='第5章「山岳追撃戦」';$('#turnLabel').textContent=S.turn;$('#phaseLabel').textContent=S.phase==='ally'?'自軍':'敵軍';$('#objectiveLabel').textContent=!S.dispatch?(S.lost?'旧記録塔を調査':'逃走する伝令を止める'):S.towers.length?'久美で出口へ離脱':'見張り台を調査';document.querySelectorAll('#map .tile').forEach(c=>{const x=+c.dataset.x,y=+c.dataset.y,k=K(x,y);c.className=`tile t-${rows[y][x]}`;if(reach.has(k))c.classList.add('move');if(attack.has(k)&&!reach.has(k))c.classList.add('attack');if(rows[y][x]==='S')c.classList.add('tower');if(S.towers.includes(k))c.classList.add('lit');if(rows[y][x]==='E')c.classList.add('exit');c.innerHTML='';});for(const u of S.units.filter(u=>u.hp>0)){const c=document.querySelector(`#map .tile[data-x="${u.x}"][data-y="${u.y}"]`);if(!c)continue;const p=document.createElement('span');p.className=`token ${u.faction}${u.acted?' acted':''}`;p.textContent=u.short;c.appendChild(p);if(u.id===sel)c.classList.add('selected');}renderCard();renderActions();renderLog();$('#endTurnButton').disabled=busy||S.phase!=='ally'||S.clear;}
function renderCard(){const c=$('#unitCard'),u=by(sel);if(!u){c.className='panel-card empty';c.innerHTML='<h2>ユニット情報</h2><p>ユニットをタップしてください。</p>';return;}c.className='panel-card';c.innerHTML=`<h2>${u.name}</h2><p>${u.className} Lv${u.lv||1} EXP ${u.exp||0}</p><p>HP ${u.hp}/${u.maxHp}　力 ${u.str}　技 ${u.skl}　速 ${u.spd}</p><p>守 ${u.def}　魔防 ${u.res}　移動 ${u.move}</p><p>装備 ${WT[u.weapon]?.name||u.weapon} (${u.uses??'-'})</p>`;}
function renderLog(){const e=$('#battleLog');if(e)e.innerHTML=S.log.slice(-10).map(t=>`<div class="log-entry">${t}</div>`).join('');}
function btn(t,f){const b=document.createElement('button');b.textContent=t;b.onclick=f;$('#actionButtons').appendChild(b);}
function renderActions(){const b=$('#actionButtons');b.innerHTML='';const u=by(sel);if(!u||u.faction!=='ally'||u.acted||S.phase!=='ally'||busy)return;const es=S.units.filter(v=>v.faction==='enemy'&&v.hp>0&&canHit(u,v));if(es.length)btn('攻撃',()=>targets(u,es));if(u.staff){const hs=S.units.filter(v=>v.faction==='ally'&&v.hp>0&&v.hp<v.maxHp&&D(u,v)===1);if(hs.length)btn('杖',()=>heals(u,hs));}const k=K(u.x,u.y);if(rows[u.y][u.x]==='S'&&!S.towers.includes(k))btn('偵察',()=>tower(u));if(rows[u.y][u.x]==='E'&&u.lord&&S.dispatch&&S.towers.length)btn('離脱',clear);btn('待機',()=>finish(u));}
function select(u){sel=u.id;if(u.faction==='ally'&&!u.acted&&S.phase==='ally'){reach=moveRange(u);attack=new Set();for(const k of reach.keys()){const [x,y]=k.split(',').map(Number);for(const a of atkFrom(x,y,u))attack.add(a);}}else{reach=new Map();attack=new Set();}render();}
function tap(x,y){if(busy||S.clear)return;const o=at(x,y),u=by(sel);if(o)return select(o);if(!u||u.faction!=='ally'||u.acted||S.phase!=='ally'||!reach.has(K(x,y)))return;u.x=x;u.y=y;reach=moveRange(u);attack=new Set();for(const k of reach.keys()){const [a,b]=k.split(',').map(Number);for(const z of atkFrom(a,b,u))attack.add(z);}render();}
function finish(u){u.acted=true;sel=null;reach=new Map();attack=new Set();save();render();}
function xp(u,n){u.exp=(u.exp||0)+n;while(u.exp>=100){u.exp-=100;u.lv=(u.lv||1)+1;u.maxHp++;u.hp++;if(Math.random()<.55)u.str++;if(Math.random()<.5)u.skl++;if(Math.random()<.5)u.spd++;log(`${u.name}はレベル${u.lv}になった。`);}}
async function hit(a,d){const w=WT[a.weapon]||WT.sword;a.uses=Math.max(0,(a.uses??30)-1);if(Math.random()*100>Math.min(98,w.hit+a.skl*2-d.spd)){log(`${a.name}の攻撃は外れた。`);return;}const p=(a.mag&&a.weapon==='light'?a.mag:a.str)+w.mt,dmg=Math.max(0,p-d.def);d.hp=Math.max(0,d.hp-dmg);log(`${a.name} → ${d.name} ${dmg}ダメージ。`);if(d.hp<=0){log(`${d.name}は戦闘不能になった。`);if(d.id==='courier'){S.dispatch=true;await story([{s:'別働隊',t:'命令書を確保した。見張り台の記録と照合しよう。'},{s:'佐々木久美',t:'よし、経路を確認する。'}],'伝令確保');}}}
async function battle(a,d){busy=true;await hit(a,d);if(d.hp>0&&canHit(d,a))await hit(d,a);xp(a,d.hp<=0?35:15);busy=false;check();save();render();}
function targets(u,es){$('#actionButtons').innerHTML='';es.forEach(e=>btn(`${e.name} HP${e.hp}`,async()=>{await battle(u,e);if(u.hp>0)finish(u);}));btn('戻る',renderActions);}
function heals(u,hs){$('#actionButtons').innerHTML='';hs.forEach(t=>btn(`${t.name} HP${t.hp}/${t.maxHp}`,()=>{const n=Math.min(t.maxHp-t.hp,14+(u.mag||0));t.hp+=n;u.uses=Math.max(0,(u.uses??30)-1);xp(u,12+Math.min(12,n));log(`${u.name}は${t.name}を${n}回復。`);finish(u);}));btn('戻る',renderActions);}
function face(name){const id=faceIds[name],src=id&&(window.HINATA_PORTRAIT_DATA||{})[id];return src?`<img src="${src}" alt="${name}">`:`<span>${name.slice(0,1)}</span>`;}
function story(lines,title=''){const o=$('#storyOverlay'),w=$('#storyWindows');if(!o||!w)return Promise.resolve();$('#storyChapter').textContent=title;o.hidden=false;let i=0;return new Promise(done=>{const draw=()=>{const l=lines[i],n=['ナレーション','作戦'].includes(l.s);w.innerHTML=n?`<div class="story-window"><div><strong>${l.s}</strong><p>${l.t}</p></div></div>`:`<div class="story-window"><div class="face">${face(l.s)}</div><div><strong>${l.s}</strong><p>${l.t}</p></div></div>`;$('#storyBack').disabled=i===0;$('#storyNext').textContent=i===lines.length-1?'閉じる':'次へ';};$('#storyBack').onclick=()=>{if(i){i--;draw();}};$('#storyNext').onclick=()=>{if(i<lines.length-1){i++;draw();}else{o.hidden=true;done();}};draw();});}
async function tower(u){const k=K(u.x,u.y);S.towers.push(k);if(S.lost)S.dispatch=true;log(`${u.name}が見張り台を調査した。`);await story([{s:u.name,t:'記録が残っている。命令の経路を確認できる。'},{s:'佐々木久美',t:'これで進路が見えた。山頂へ向かおう。'}],'見張り台');finish(u);}
function best(u,p){const r=moveRange(u);let z={x:u.x,y:u.y},sc=D(u,p);for(const k of r.keys()){const [x,y]=k.split(',').map(Number);if(at(x,y)&&!(x===u.x&&y===u.y))continue;const n=Math.abs(x-p.x)+Math.abs(y-p.y);if(n<sc){sc=n;z={x,y};}}return z;}
async function enemyTurn(){busy=true;S.phase='enemy';render();for(const e of S.units.filter(u=>u.faction==='enemy'&&u.hp>0)){if(e.sleep&&S.turn<3)continue;if(e.id==='courier'){const q=best(e,{x:14,y:1});e.x=q.x;e.y=q.y;if(e.x===14&&e.y===1){e.hp=0;S.lost=true;log('敵伝令が山頂へ逃げ込んだ。旧記録塔から追跡できる。');}render();await new Promise(r=>setTimeout(r,100));continue;}const as=S.units.filter(u=>u.faction==='ally'&&u.hp>0);if(!as.length)break;let t=as.slice().sort((a,b)=>D(e,a)-D(e,b))[0];if(!canHit(e,t)){const q=best(e,t);e.x=q.x;e.y=q.y;render();await new Promise(r=>setTimeout(r,80));}t=as.filter(a=>canHit(e,a)).sort((a,b)=>a.hp-b.hp)[0];if(t)await hit(e,t);check();}busy=false;if(!S.clear){S.turn++;S.phase='ally';S.units.filter(u=>u.faction==='ally'&&u.hp>0).forEach(u=>u.acted=false);if(S.turn===3)log('待機していた敵部隊が動き始めた。');save();render();toast(`ターン ${S.turn}`);}}
function check(){const k=by('kumi');if(!k||k.hp<=0){busy=true;$('#modalContent').innerHTML='<h2>敗北</h2><p>久美が戦闘不能になった。</p><button id="retry5">第5章をやり直す</button>';$('#modal').showModal();$('#retry5').onclick=()=>{localStorage.removeItem(SAVE);location.reload();};}}
async function clear(){if(S.clear)return;S.clear=true;await story([{s:'ナレーション',t:'山頂へ抜け、追跡の手掛かりを確保した。'},{s:'佐々木久美',t:'ここで止まらない。次へ進もう。'}],'山頂');if(!TRIAL){const r=S.units.filter(u=>u.faction==='ally'&&u.hp>0&&!u.guest).map(u=>{const c={...u,hp:u.maxHp,acted:false};delete c.x;delete c.y;return c;});window.HinataCampaign?.saveRoster?.(5,r,{flags:{chapter5Cleared:true}});}save();$('#modalContent').innerHTML=`<h2>第5章クリア</h2><button id="next5">${TRIAL?'試遊を終了':'次章へ進む'}</button>`;$('#modal').showModal();$('#next5').onclick=()=>location.href=TRIAL?'../':'../chapter6/';}
function css(){const s=document.createElement('style');s.textContent=`#map .tile{position:relative;background:#596b50;border:1px solid #29352a}#map .t-\#{background:#222b27}#map .t-f{background:#355b3d}#map .t-m{background:#6b6251}#map .t-r,#map .t-B{background:#897452}#map .t-\~{background:#315e80}#map .t-V{background:#705b43}#map .t-S{background:#584a73}#map .t-E{background:#77691f}.token{position:absolute;inset:10%;display:grid;place-items:center;border-radius:50%;z-index:4;font-weight:900}.token.ally{background:#245fb7;color:#fff;border:2px solid #c9e4ff}.token.enemy{background:#9d3636;color:#fff;border:2px solid #ffd0ca}.token.acted{opacity:.5;filter:grayscale(.8)}#map .move{box-shadow:inset 0 0 0 4px #3791ff!important}#map .attack:not(.move){box-shadow:inset 0 0 0 4px #e64b4b!important}#map .selected{outline:3px solid #fff18a;outline-offset:-3px}#map .tower:after{content:'塔';position:absolute;right:2px;bottom:1px;color:#fff;font-size:10px}.story-window{display:flex;gap:12px;align-items:center}.face{width:80px;height:80px;flex:0 0 80px;border:3px solid #d6bd6d;background:#17233d;display:grid;place-items:center;font-size:30px;color:#fff}.face img{width:100%;height:100%;object-fit:cover}`;document.head.appendChild(s);}
async function start(){css();build();$('#endTurnButton').onclick=()=>!busy&&S.phase==='ally'&&enemyTurn();$('#menuButton').onclick=()=>{$('#modalContent').innerHTML='<h2>メニュー</h2><button id="save5">セーブ</button> <button id="reset5">第5章を最初から</button>';$('#modal').showModal();$('#save5').onclick=()=>{save();$('#modal').close();toast('セーブしました');};$('#reset5').onclick=()=>{if(confirm('第5章を最初からやり直しますか？')){localStorage.removeItem(SAVE);location.reload();}};};render();if(!S.flags.intro){S.flags.intro=true;await story([{s:'ナレーション',t:'一行は山道へ入った。敵の伝令と分断された味方が、同じ山中を進んでいる。'},{s:'佐々木久美',t:'離れた仲間を守りながら伝令を止める。全部倒す必要はない。'},{s:'加藤史帆',t:'必要な場所を押さえて、先へ抜けよう。'},{s:'潮紗理菜',t:'傷ついたら戻って。私が回復します。'},{s:'作戦',t:'伝令を止め、見張り台を調査し、久美を山頂出口へ到達させよ。'}],'第5章');save();render();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();