window.hiddenPool=window.hiddenPool||[
{name:"佐々木美玲",lead:83,war:76,int:84,pol:90,cha:97,skill:"パンの施し",desc:"兵糧と民忠を増やす"},{name:"高本彩花",lead:78,war:84,int:76,pol:72,cha:94,skill:"おたけ奇襲",desc:"策略に強い"},{name:"宮田愛萌",lead:66,war:52,int:96,pol:94,cha:95,skill:"雅なる説客",desc:"敵将登用に強い"},{name:"森本茉莉",lead:72,war:73,int:89,pol:80,cha:92,skill:"天才の閃き",desc:"捜索に強い"},{name:"山口陽世",lead:85,war:91,int:75,pol:64,cha:88,skill:"剛球突破",desc:"接戦で強い"},{name:"正源司陽子",lead:88,war:82,int:93,pol:86,cha:98,skill:"新星の号令",desc:"軍勢の士気を高める"}
];
officers.forEach(o=>{if(o.moved==null)o.moved=false});
function choose(title,items,fn,label=x=>x){popup(title,"選択してください。",items.map(x=>({t:label(x),fn:()=>fn(x)})).concat([{t:"戻る"}]))}
function render(){const c=cities[selected];document.getElementById("status").innerHTML=`<b>${turn}月</b>　支配 ${mine().length}/7都市<br>選択：<b>${selected}</b> ${badge(c.r)}<br>金 ${c.g}　兵糧 ${c.f}<br>兵 ${c.s.toLocaleString()}　訓練 ${c.t}<br>総兵力：${mine().reduce((a,x)=>a+cities[x].s,0).toLocaleString()}<br>配下：${army().length}人`;
document.getElementById("roster").innerHTML=army().map(o=>`<div class="officer"><b>${o.name}</b>（${o.c}）${o.moved?"・移動済":""}<br>統${o.lead} 武${o.war} 知${o.int} 政${o.pol} 魅${o.cha} 忠${o.loy}<br><span class="skill">${o.skill}</span>：${o.desc}</div>`).join("");
document.getElementById("event").innerHTML=eventText?`<div class="event"><b>今月の情勢</b><br>${eventText}</div>`:"";
document.getElementById("map").innerHTML=Object.entries(cities).map(([n,x])=>`<div class="city ${x.r==="久美軍"?"mine":"enemy"} ${n===selected?"sel":""}" role="button" tabindex="0" data-city="${n}"><div class="name">${n}</div>${badge(x.r)}<div class="stats">金 ${x.g}　兵糧 ${x.f}<br>兵 ${x.s.toLocaleString()}　民忠 ${x.l}<br>開発 ${x.d}　訓練 ${x.t}<div class="meter"><i style="width:${Math.min(100,x.s/100)}%"></i></div>武将：${ofs(n).map(o=>o.name+(o.f==="在野"?"★":"")).join("、")||"なし"}<br>隣接：${x.n.join("・")}</div></div>`).join("");
let dis=c.r!=="久美軍"||c.acted||over,targets=c.n.filter(n=>cities[n].r!=="久美軍");document.getElementById("commands").innerHTML=`<button data-action="develop" ${dis?"disabled":""}>内政</button><button data-action="recruit" ${dis?"disabled":""}>徴兵</button><button data-action="train" ${dis?"disabled":""}>訓練</button><button data-action="search" ${dis?"disabled":""}>捜索</button><button data-action="hire" ${dis?"disabled":""}>在野登用</button><button data-action="enemyHire" ${dis?"disabled":""}>敵将登用</button><button data-action="strategy" ${dis?"disabled":""}>策略</button><button data-action="move" ${c.r!=="久美軍"||over?"disabled":""}>武将移動</button>${targets.map(n=>`<button data-action="attack" data-target="${n}" ${dis?"disabled":""}>${n}へ出陣</button>`).join("")}<button data-action="next" ${over?"disabled":""}>ターン終了</button>`;document.getElementById("log").textContent=logs.join("\n");checkEnd()}
function searchCity(){let c=cities[selected];if(c.g<60)return popup("資金不足","捜索には金60が必要。",[{t:"戻る"}]);c.g-=60;let scout=best(selected,"int"),chance=50+(scout?.int||55)/3;if(window.hiddenPool.length&&Math.random()*100<chance){let i=Math.floor(Math.random()*window.hiddenPool.length),o=window.hiddenPool.splice(i,1)[0];officers.push({...o,f:"在野",c:selected,loy:38,moved:false});addLog(`${scout?.name||"役人"}が${selected}で${o.name}を発見。`);popup("人材発見",`<b>${o.name}</b>を発見！<br><span class="skill">${o.skill}</span>：${o.desc}`,[{t:"よし"}])}else{let n=100+Math.floor(Math.random()*180);if(Math.random()<.55){c.g+=n;addLog(`${selected}の捜索で金${n}を発見。`)}else{c.f+=n*2;addLog(`${selected}の捜索で兵糧${n*2}を確保。`)}}act()}
function enemyHire(){let cand=officers.filter(o=>o.f!=="久美軍"&&o.f!=="在野");if(!cand.length)return popup("対象なし","敵将がいない。",[{t:"戻る"}]);choose("引き抜く敵将",cand,o=>attemptEnemyHire(o),o=>`${o.name}（${o.f}・${o.c}・忠誠${o.loy}）`)}
function attemptEnemyHire(o){let c=cities[selected];if(c.g<120)return popup("資金不足","敵将登用には金120が必要。",[{t:"戻る"}]);c.g-=120;let r=best(selected,"cha"),chance=Math.max(5,52-o.loy/1.7+(r?.cha||70)-80+(r?.name==="加藤史帆"?15:0)+(r?.name==="宮田愛萌"?25:0));if(Math.random()*100<chance){let old=o.f;o.f="久美軍";o.c=selected;o.loy=68;o.moved=true;addLog(`${r?.name||"使者"}が${old}の${o.name}を引き抜いた！`);popup("登用成功",`${o.name}が久美軍に加わった。`,[{t:"歓迎"}])}else{addLog(`${o.name}の引き抜きに失敗。`);o.loy=Math.min(100,o.loy+4)}act()}
function moveOfficer(){let cand=ofs(selected,"久美軍").filter(o=>!o.moved);if(!cand.length)return popup("移動不可","移動できる武将がいない。",[{t:"戻る"}]);choose("移動する武将",cand,o=>{let dest=mine().filter(n=>n!==selected);if(!dest.length)return popup("移動先なし","他の自軍都市がない。",[{t:"戻る"}]);choose("移動先",dest,n=>{let from=o.c;o.c=n;o.moved=true;addLog(`${o.name}が${from}から${n}へ移動。`);render()})},o=>`${o.name}（${o.c}）`)}
function strategy(){let c=cities[selected],targets=c.n.filter(n=>cities[n].r!=="久美軍");if(c.g<100)return popup("資金不足","策略には金100が必要。",[{t:"戻る"}]);if(!targets.length)return popup("対象なし","隣接する敵都市がない。",[{t:"戻る"}]);choose("策略",["流言","焼討","偽報","離間"],kind=>choose("対象都市",targets,t=>executeStrategy(kind,t)))}
function executeStrategy(kind,t){let c=cities[selected],d=cities[t],intel=avg(ofs(selected,"久美軍").map(o=>o.int)),def=avg(ofs(t,d.r).map(o=>o.int));c.g-=100;let ok=Math.random()*100<55+(intel-def)*.7;if(ok&&kind==="流言"){ofs(t,d.r).forEach(o=>o.loy=Math.max(20,o.loy-15));addLog(`${t}に流言成功。敵将忠誠低下。`)}else if(ok&&kind==="焼討"){let n=250+Math.floor(intel*3);d.f=Math.max(0,d.f-n);addLog(`${t}を焼討。兵糧-${n}。`)}else if(ok&&kind==="偽報"){let n=400+Math.floor(intel*4);d.s=Math.max(500,d.s-n);d.t=Math.max(20,d.t-10);addLog(`${t}に偽報成功。兵-${n}、訓練-10。`)}else if(ok){let o=ofs(t,d.r).slice().sort((a,b)=>a.loy-b.loy)[0];if(o&&o.loy<78){o.f="在野";o.loy=35;addLog(`離間成功。${o.name}が在野となった。`)}else addLog(`${t}への離間は不発。`)}else addLog(`${t}への策略は看破された。`);act()}
const oldNextTurn=nextTurn;nextTurn=function(){officers.forEach(o=>o.moved=false);oldNextTurn()};
const oldRestart=restart;restart=function(){window.hiddenPool=[{name:"佐々木美玲",lead:83,war:76,int:84,pol:90,cha:97,skill:"パンの施し",desc:"兵糧と民忠を増やす"},{name:"高本彩花",lead:78,war:84,int:76,pol:72,cha:94,skill:"おたけ奇襲",desc:"策略に強い"},{name:"宮田愛萌",lead:66,war:52,int:96,pol:94,cha:95,skill:"雅なる説客",desc:"敵将登用に強い"},{name:"森本茉莉",lead:72,war:73,int:89,pol:80,cha:92,skill:"天才の閃き",desc:"捜索に強い"},{name:"山口陽世",lead:85,war:91,int:75,pol:64,cha:88,skill:"剛球突破",desc:"接戦で強い"},{name:"正源司陽子",lead:88,war:82,int:93,pol:86,cha:98,skill:"新星の号令",desc:"軍勢の士気を高める"}];oldRestart()};
handleAction=function(el){const action=el.dataset.action;if(!action||el.disabled)return;const actions={save:saveGame,load:loadGame,restart,develop,recruit,train:trainCity,search:searchCity,hire,enemyHire,strategy,move:moveOfficer,next:nextTurn};if(action==="attack")return attack(el.dataset.target);if(actions[action])actions[action]()};
render();