const fs=require('fs'),vm=require('vm'),assert=require('assert');
global.document={querySelector:()=>null,getElementById:()=>null};
global.closeModal=()=>{};global.log=msg=>state.logs.unshift(msg);
global.state={selected:'小沛',cities:{'小沛':{name:'小沛',force:'日向軍'}},logs:[],rogue:{converted:0,captures:0,rewardQueue:[],rewardOpen:false,startCity:'小沛'},officers:[{name:'齊藤京子',force:'日向軍',city:'小沛',status:'一般',loy:72,acted:0}]};
global.window={HINATA_CANONICAL_STATS:{'佐々木久美':{},'齊藤京子':{},'柿崎芽実':{},'宮田愛萌':{}},render:()=>{const o=state.officers[0];if(o.force==='日向軍'){o.force='退場';o.status='戦利品';state.rogue.converted++;state.rogue.rewardQueue.push({type:'officer',officer:{name:o.name}})}},endBattle:()=>{},showModal:()=>{}};
vm.runInThisContext(fs.readFileSync('sangokushi/rogue/rogue_identity_v12.js','utf8'),{filename:'rogue_identity_v12.js'});
const api=window.HINATA_ROGUE_IDENTITY_V12_API;assert(api,'identity v12 API missing');
assert(api.isHinata('齊藤京子'),'Saito Kyoko must be canonical Hinata');
assert(api.isHinata('齊藤 京子'),'normalized Saito name must be canonical Hinata');
assert(api.isHinata('柿崎芽実'),'graduated first-generation member must remain canonical Hinata');
assert(api.isHinata('宮田愛萌'),'graduated member must remain canonical Hinata');
window.render();
assert.strictEqual(state.officers[0].force,'日向軍','legacy scrub must not remove canonical Hinata from own roster');
assert.notStrictEqual(state.officers[0].status,'戦利品','canonical Hinata must not remain spoils');
assert.strictEqual(state.rogue.converted,0,'false conversion count must be rolled back');
assert.strictEqual(state.rogue.rewardQueue.length,0,'false conversion reward must be removed');
const o=state.officers[0];o.force='退場';o.status='戦利品';o.city='';o.loy=0;state.rogue.converted=1;state.rogue.captures=1;state.rogue.rewardQueue=[{type:'officer',officer:{name:'齊藤京子'}}];state.logs=['齊藤京子は捕縛後、日向軍の恒久配下にはならず戦利品となった。'];
const fixed=api.repairMisclassified('小沛');
assert(fixed.includes('齊藤京子'),'misclassified Saito save must be repaired');
assert.strictEqual(o.force,'在野');assert.strictEqual(o.status,'在野');assert.strictEqual(o.city,'小沛');
assert.strictEqual(state.rogue.converted,0);assert.strictEqual(state.rogue.captures,0);assert.strictEqual(state.rogue.rewardQueue.length,0);
console.log('ROGUE v0.12 canonical Hinata identity regression: PASS');
