const fs=require('fs'),vm=require('vm'),assert=require('assert');
const path=require('path');
const file=path.join(__dirname,'..','rogue.js');
const src=fs.readFileSync(file,'utf8');
const sandbox={window:{},console};vm.createContext(sandbox);vm.runInContext(src,sandbox,{filename:'rogue.js'});
const R=sandbox.window.HINATA_ROGUE_RULES;assert(R,'ROGUE rules API missing');
assert.equal(R.SAVE_KEY,'hinataSangokushiRogueV1');assert.notEqual(R.SAVE_KEY,'hinataSangokushiV1','base game save key must remain separate');
assert.equal(R.THIRD.length,4);assert(R.THIRD.some(x=>x.name==='髙橋未来虹'&&x.skill==='大将の器'));
assert.equal(R.UPGRADE_POOL.length,30,'prototype should ship with 30 run upgrades');assert.equal(new Set(R.UPGRADE_POOL.map(x=>x.id)).size,30,'upgrade ids must be unique');
assert.deepEqual(JSON.parse(JSON.stringify(R.metaBonuses(0))),{level:0,gold:0,troops:0,rerolls:0});
assert.equal(R.metaBonuses(100).level,1);assert.equal(R.metaBonuses(100).gold,100);assert.equal(R.metaBonuses(150).rerolls,1);assert.equal(R.metaBonuses(10000).rerolls,3);
assert.equal(R.gearFor({name:'曹操',lead:99,war:88,int:92,pol:97,cha:98}).name,'倚天の剣');
assert.equal(R.gearFor({name:'関羽',lead:100,war:98,int:82,pol:65,cha:96}).name,'青龍偃月刀');
assert.equal(R.gearFor({name:'諸葛亮',lead:97,war:55,int:100,pol:96,cha:96}).stat,'int');
assert(src.includes("o.force='退場'"),'historical officers must be retired instead of joining permanent roster');
assert(src.includes("state.rogue.finalBossCity"),'12-month final battle state missing');
assert(src.includes("[4,7,10]"),'quarterly/random build reward milestones missing');
assert(src.includes("isHinata(t.name)?'日向坂メンバー→登用':'歴史武将→戦利品化'"),'hire conversion rule missing');
console.log('rogue_rules_test: PASS');