// 日向三國志 ROGUE Prototype 0.1
(()=>{
const SAVE_KEY='hinataSangokushiRogueV1',META_KEY='hinataSangokushiRogueMetaV1';
const THIRD=[
 {name:'髙橋未来虹',lead:96,war:90,int:84,pol:75,cha:90,status:'君主',apt:'槍兵',skill:'大将の器'},
 {name:'上村ひなの',lead:78,war:52,int:95,pol:84,cha:92,status:'一般',apt:'弩兵',skill:'星詠み'},
 {name:'森本茉莉',lead:84,war:78,int:82,pol:80,cha:90,status:'一般',apt:'剣盾兵'},
 {name:'山口陽世',lead:90,war:93,int:66,pol:70,cha:90,status:'一般',apt:'騎兵'}
];
const START_BACK={
 '佐々木久美':{force:'袁紹',city:'南皮',loy:82,status:'一般',apt:'剣盾兵'},
 '加藤史帆':{force:'曹操',city:'許昌',loy:78,status:'一般',apt:'騎兵'},
 '齊藤京子':{force:'劉備',city:'小沛',loy:78,status:'一般',apt:'弩兵'},
 '井口眞緒':{force:'在野',city:'平原',loy:42,status:'在野',apt:'剣盾兵'}
};
const FAMOUS_GEAR={
 '曹操':{name:'倚天の剣',stat:'lead',amount:8,desc:'統率＋8'},'関羽':{name:'青龍偃月刀',stat:'war',amount:10,desc:'武力＋10'},
 '呂布':{name:'方天画戟',stat:'war',amount:12,desc:'武力＋12'},'諸葛亮':{name:'兵法二十四篇',stat:'int',amount:12,desc:'知力＋12'},
 '周瑜':{name:'赤壁火計書',stat:'int',amount:10,desc:'知力＋10'},'趙雲':{name:'龍胆',stat:'war',amount:9,desc:'武力＋9'},
 '司馬懿':{name:'狼顧の兵法',stat:'int',amount:10,desc:'知力＋10'},'張遼':{name:'遼来々の旗',stat:'lead',amount:9,desc:'統率＋9'},
 '孫策':{name:'小覇王の槍',stat:'war',amount:9,desc:'武力＋9'},'馬超':{name:'錦馬超の鞍',stat:'lead',amount:8,desc:'統率＋8'},
 '許褚':{name:'虎痴の鎧',stat:'war',amount:8,desc:'武力＋8'},'典韋':{name:'双鉄戟',stat:'war',amount:9,desc:'武力＋9'}
};
const UPGRADE_POOL=[
 ['attack8','全軍猛攻','日向軍の通常攻撃＋8%'],['cavalry12','騎兵突撃','騎兵の通常攻撃＋12%'],['spear12','槍衾強化','槍兵の通常攻撃＋12%'],['bow12','弩兵強化','弩兵の通常攻撃＋12%'],['shield12','剣盾堅陣','剣盾兵の通常攻撃＋12%'],
 ['wall15','破城心得','城壁・門への通常攻撃＋15%'],['high10','高揚攻勢','士気80以上の通常攻撃＋10%'],['low15','背水の陣','士気30未満の通常攻撃＋15%'],['third8','三期の絆','三期生連携中の通常攻撃をさらに＋8%'],['fifth8','五期の絆','五期生連携中の通常攻撃をさらに＋8%'],
 ['lead2','統率鍛錬','現在の味方全員の統率＋2'],['war2','武勇鍛錬','現在の味方全員の武力＋2'],['int2','智謀鍛錬','現在の味方全員の知力＋2'],['pol2','政略鍛錬','現在の味方全員の政治＋2'],['cha2','人望鍛錬','現在の味方全員の魅力＋2'],
 ['mikuni4','大将修練','髙橋未来虹の統率＋4'],['hinano4','星詠修練','上村ひなのの知力＋4'],['mari4','前衛指揮','森本茉莉の統率＋4'],['haruyo4','遊撃修練','山口陽世の武力＋4'],['spirit10','闘志充填','各戦闘の初期戦意＋10'],
 ['morale8','士気高揚','各戦闘の初期士気＋8'],['heal8','野戦治療','勝利後、残存兵の8%が復帰'],['capture15','捕縛術','歴史武将の捕縛率＋15%'],['gold15','商隊確保','月収の金を追加で15%獲得'],['food15','屯田強化','月収の兵糧を追加で15%獲得'],
 ['move1','神速行軍','味方部隊の移動補正＋1'],['objective12','拠点戦巧者','拠点上からの通常攻撃＋12%'],['boss15','決戦兵法','12月の最終決戦で通常攻撃＋15%'],['reroll','運命改変','強化3択のリロール回数＋1'],['repair10','城塞修復','勝利して得た城の城壁＋10']
].map(([id,name,desc])=>({id,name,desc}));
function metaBonuses(total){const lv=Math.floor((Number(total)||0)/100);return{level:lv,gold:Math.min(1000,lv*100),troops:Math.min(1000,lv*100),rerolls:Math.min(3,Math.floor((Number(total)||0)/150))}}
function strongestStat(o){return ['lead','war','int','pol','cha'].sort((a,b)=>(Number(o?.[b])||0)-(Number(o?.[a])||0))[0]||'war'}
function genericGear(o){const stat=strongestStat(o),labels={lead:'指揮佩',war:'武勇佩',int:'智謀書',pol:'政略印',cha:'人望珠'};return{name:`${o.name}の${labels[stat]}`,stat,amount:6,desc:`${{lead:'統率',war:'武力',int:'知力',pol:'政治',cha:'魅力'}[stat]}＋6`}}
function gearFor(o){return FAMOUS_GEAR[o?.name]||genericGear(o||{name:'武将',war:50})}
window.HINATA_ROGUE_RULES={SAVE_KEY,META_KEY,THIRD,FAMOUS_GEAR,UPGRADE_POOL,metaBonuses,strongestStat,gearFor};
if(typeof document==='undefined')return;

const baseStartScreen=window.startScreen,baseBeginGame=window.beginGame,baseRender=window.render,baseEndBattle=window.endBattle,baseEndMonth=window.endMonth,baseBeginBattle=window.beginBattle;
const V39=window.V2439||{},baseNormalDamage=typeof V39.normalDamage==='function'?V39.normalDamage:null;
let startChoices=[];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function hinataNames(){const s=new Set(THIRD.map(x=>x.name));try{(HINATA_START||[]).forEach(o=>s.add(o.name))}catch(e){}try{(HINATA_WORLD||[]).forEach(x=>s.add(x[0]))}catch(e){}try{(window.V2458?.FIFTH||[]).forEach(o=>s.add(o.name))}catch(e){}return s}
function isHinata(name){return hinataNames().has(name)}
function loadMeta(){try{return JSON.parse(localStorage.getItem(META_KEY)||'null')||{total:0,runs:0,clears:0}}catch(e){return{total:0,runs:0,clears:0}}}
function saveMeta(m){localStorage.setItem(META_KEY,JSON.stringify(m))}
function mods(){state.rogue.mods=state.rogue.mods||{};return state.rogue.mods}
function initMods(){return{attack:0,cavalry:0,spear:0,bow:0,shield:0,wall:0,high:0,low:0,third:0,fifth:0,startSpirit:0,startMorale:0,postBattleHeal:0,captureBonus:0,gold:0,food:0,move:0,objective:0,boss:0,postWall:0,statLead:0,statWar:0,statInt:0,statPol:0,statCha:0}}
function statLabel(k){return{lead:'統率',war:'武力',int:'知力',pol:'政治',cha:'魅力'}[k]||k}
function playerHinata(){return (state?.officers||[]).filter(o=>o.force==='日向軍'&&isHinata(o.name)&&o.status!=='死亡'&&o.status!=='捕虜')}
function applyStoredStats(o){if(!o||!isHinata(o.name))return;o.vRogueStatApplied=o.vRogueStatApplied||{};const m=mods();for(const k of ['lead','war','int','pol','cha']){const key='stat'+k[0].toUpperCase()+k.slice(1),want=Number(m[key])||0,had=Number(o.vRogueStatApplied[k])||0;if(want>had){o[k]=(Number(o[k])||0)+(want-had);o.vRogueStatApplied[k]=want}}}
function boostAll(k,n){const key='stat'+k[0].toUpperCase()+k.slice(1);mods()[key]=(Number(mods()[key])||0)+n;for(const o of playerHinata()){o[k]=(Number(o[k])||0)+n;o.vRogueStatApplied=o.vRogueStatApplied||{};o.vRogueStatApplied[k]=(Number(o.vRogueStatApplied[k])||0)+n}}
function boostMember(name,k,n){const o=(state.officers||[]).find(x=>x.name===name);if(o)o[k]=(Number(o[k])||0)+n}
function meta(){return state?.rogue?.meta||loadMeta()}
function currentBonus(){return metaBonuses(meta().total)}
function chooseStartCities(){const cs=buildCities(),empty=Object.values(cs).filter(c=>!c.force);startChoices=shuffle(empty).slice(0,3);return{cs,choices:startChoices}}
function rogueStartScreen(){
 state=null;const {cs,choices}=chooseStartCities(),m=loadMeta(),b=metaBonuses(m.total);
 app.innerHTML=`<div class="rogue-start"><section class="panel"><div class="rogue-title">十二か月戦記</div><p>髙橋未来虹・上村ひなの・森本茉莉・山口陽世の三期生4人で旗揚げ。敵の歴史武将は配下にせず、装備・強化素材へ変換する。</p><div class="rogue-meta"><div>陽だまりPt<b>${m.total}</b></div><div>ラン回数<b>${m.runs}</b></div><div>クリア<b>${m.clears}</b></div></div><div class="rogue-help">恒久ボーナス Lv${b.level}：開始金＋${b.gold}／開始兵＋${b.troops}／3択リロール＋${b.rerolls}<br>強化候補・日向坂メンバーの配置・捕縛武将が毎ラン変化します。</div><div class="title">今回の開始候補</div><div class="rogue-city-options">${choices.map(c=>`<button data-rogue-start="${c.name}"><b>${c.name}</b><small>隣接${c.n.length}　初期難度★${Math.min(6,1+c.n.filter(n=>cs[n]?.force).length)}</small></button>`).join('')}</div></section><section class="panel"><div class="title">今回のルール</div><div class="rogue-help"><b>味方として使えるのは日向坂46メンバーだけ。</b><br><br>歴史武将を調略・捕縛すると、①その武将由来の装備にする、②日向坂メンバーの能力強化素材として消費する、のどちらかを選びます。<br><br>城攻略と3か月ごとにランダム強化3択。12月に国境の強敵都市が「最終決戦地」になります。12月中に落とせばランクリア。</div><div class="title">初期メンバー</div>${THIRD.map(o=>`<div class="officer"><span class="face">${o.name[0]}</span><div><b>${o.name}</b><small> 統${o.lead} 武${o.war} 知${o.int} 政${o.pol} 魅${o.cha}</small></div></div>`).join('')}</section></div>`;
 document.querySelectorAll('[data-rogue-start]').forEach(btn=>btn.onclick=()=>beginRogue(btn.dataset.rogueStart));
}
function randomizeHinataWorld(start){
 const names=hinataNames(),third=new Set(THIRD.map(x=>x.name)),cities=Object.values(state.cities),spots=shuffle(cities);
 let i=0;for(const o of state.officers){if(!names.has(o.name)||third.has(o.name)||o.status==='死亡')continue;const c=spots[i++%spots.length];o.city=c.name;if(c.force==='日向軍'||!c.force||Math.random()<.42){o.force='在野';o.status='在野';o.loy=35+Math.floor(Math.random()*25)}else{o.force=c.force;o.status='一般';o.loy=60+Math.floor(Math.random()*25)}o.acted=0}
}
function ensureThird(start){for(const d of THIRD){let o=state.officers.find(x=>x.name===d.name);if(!o){o={name:d.name};state.officers.push(o)}Object.assign(o,d,{force:'日向軍',city:start,loy:d.name==='髙橋未来虹'?100:96,status:d.name==='髙橋未来虹'?'君主':'一般',type:d.apt,acted:0})}}
function beginRogue(city){
 startCity=city;baseBeginGame();state.modeId='rogue';state.rulerName='髙橋未来虹';state.selected=city;
 for(const [name,d] of Object.entries(START_BACK)){const o=state.officers.find(x=>x.name===name);if(o)Object.assign(o,d,{type:d.apt,acted:0})}
 ensureThird(city);try{for(const d of window.V2458?.FIFTH||[])window.V2458.applyOne(d)}catch(e){console.warn(e)}
 randomizeHinataWorld(city);ensureThird(city);
 const m=loadMeta(),b=metaBonuses(m.total);state.rogue={version:1,meta:m,startCity:city,startTurn:state.turn,deadline:12,finalBossCity:null,finalCleared:false,ended:false,converted:0,captures:0,upgrades:[],upgradeIds:{},items:[],rewardQueue:[],rewardOpen:false,rerolls:b.rerolls,mods:initMods()};
 const home=state.cities[city];home.force='日向軍';home.gold=1800+b.gold;home.food=22000;home.troops=5200+b.troops;home.morale=78;
 state.logs=[];log(`${city}で三期生4人が旗揚げ。十二か月戦記が始まった。`);log('歴史武将は恒久配下にならず、捕縛・調略時に装備か強化素材へ変換される。');render();setTimeout(()=>queueUpgrade('旗揚げボーナス'),250);
}
function upgradeById(id){return UPGRADE_POOL.find(x=>x.id===id)}
function applyUpgrade(id){const u=upgradeById(id);if(!u)return;const m=mods();state.rogue.upgradeIds[id]=(state.rogue.upgradeIds[id]||0)+1;state.rogue.upgrades.push(u.name);
 switch(id){case'attack8':m.attack+=.08;break;case'cavalry12':m.cavalry+=.12;break;case'spear12':m.spear+=.12;break;case'bow12':m.bow+=.12;break;case'shield12':m.shield+=.12;break;case'wall15':m.wall+=.15;break;case'high10':m.high+=.10;break;case'low15':m.low+=.15;break;case'third8':m.third+=.08;break;case'fifth8':m.fifth+=.08;break;case'lead2':boostAll('lead',2);break;case'war2':boostAll('war',2);break;case'int2':boostAll('int',2);break;case'pol2':boostAll('pol',2);break;case'cha2':boostAll('cha',2);break;case'mikuni4':boostMember('髙橋未来虹','lead',4);break;case'hinano4':boostMember('上村ひなの','int',4);break;case'mari4':boostMember('森本茉莉','lead',4);break;case'haruyo4':boostMember('山口陽世','war',4);break;case'spirit10':m.startSpirit+=10;break;case'morale8':m.startMorale+=8;break;case'heal8':m.postBattleHeal+=.08;break;case'capture15':m.captureBonus+=.15;break;case'gold15':m.gold+=.15;break;case'food15':m.food+=.15;break;case'move1':m.move+=1;break;case'objective12':m.objective+=.12;break;case'boss15':m.boss+=.15;break;case'reroll':state.rogue.rerolls++;break;case'repair10':m.postWall+=10;break}
 log(`ラン強化「${u.name}」を獲得。`);state.rogue.rewardOpen=false;closeModal();render();setTimeout(pumpRewards,80)}
function randomUpgrades(){return shuffle(UPGRADE_POOL).slice(0,3)}
function showUpgrade(reason){let choices=randomUpgrades();state.rogue.rewardOpen=true;const draw=()=>{showModal(`<h2>ラン強化：${reason}</h2><p>今回のランだけ有効。1つ選択してください。</p><div class="rogue-choice-grid">${choices.map(u=>`<button data-rogue-up="${u.id}"><b>${u.name}</b><small>${u.desc}</small></button>`).join('')}</div>${state.rogue.rerolls>0?`<button id="rogueReroll">リロール（残り${state.rogue.rerolls}）</button>`:''}`);modalCard.querySelectorAll('[data-rogue-up]').forEach(b=>b.onclick=()=>applyUpgrade(b.dataset.rogueUp));const rr=modalCard.querySelector('#rogueReroll');if(rr)rr.onclick=()=>{state.rogue.rerolls--;choices=randomUpgrades();draw()}};draw()}
function queueReward(r){if(!state?.rogue||state.rogue.ended)return;state.rogue.rewardQueue.push(r);setTimeout(pumpRewards,100)}
function queueUpgrade(reason){queueReward({type:'upgrade',reason})}
function pumpRewards(){if(!state?.rogue||state.rogue.ended||state.battle||state.rogue.rewardOpen||!state.rogue.rewardQueue.length)return;const r=state.rogue.rewardQueue.shift();if(r.type==='upgrade')showUpgrade(r.reason);else if(r.type==='officer')showOfficerConversion(r)}
function chooseMember(title,cb){const xs=playerHinata();showModal(`<h2>${title}</h2><div class="choice-list">${xs.map(o=>`<button data-rogue-member="${o.name}"><b>${o.name}</b> 統${o.lead} 武${o.war} 知${o.int} 政${o.pol} 魅${o.cha}${o.rogueEquip?`<br><small>装備：${o.rogueEquip.name}</small>`:''}</button>`).join('')}</div>`);modalCard.querySelectorAll('[data-rogue-member]').forEach(b=>b.onclick=()=>{const o=xs.find(x=>x.name===b.dataset.rogueMember);cb(o)})}
function equipMember(target,gear,source){if(target.rogueEquip){const old=target.rogueEquip;target[old.stat]=Math.max(1,(Number(target[old.stat])||0)-Number(old.amount||0))}target[gear.stat]=(Number(target[gear.stat])||0)+gear.amount;target.rogueEquip={...gear,source};state.rogue.items.push(`${target.name}：${gear.name}`);log(`${source}を装備「${gear.name}」へ変換し、${target.name}が装備。`);finishReward()}
function materialMember(target,sourceOfficer){const k=strongestStat(sourceOfficer),n=4;target[k]=(Number(target[k])||0)+n;log(`${sourceOfficer.name}を${statLabel(k)}の強化素材として消費。${target.name}の${statLabel(k)}＋${n}。`);finishReward()}
function finishReward(){state.rogue.rewardOpen=false;closeModal();render();setTimeout(pumpRewards,80)}
function showOfficerConversion(r){const o=r.officer,gear=gearFor(o);state.rogue.rewardOpen=true;showModal(`<h2>捕縛：${o.name}</h2><p>${o.name}は配下にはなりません。戦力へ変換します。</p><div class="rogue-choice-grid"><button id="rogueEquip"><b>装備化：${gear.name}</b><small>${gear.desc}。選んだ日向坂メンバー1人が装備。装備枠は1人1つで、新装備時は交換。</small></button><button id="rogueMaterial"><b>強化素材化：${statLabel(strongestStat(o))}の結晶</b><small>選んだ日向坂メンバー1人の${statLabel(strongestStat(o))}を＋4。このラン中は永続。</small></button></div>`);modalCard.querySelector('#rogueEquip').onclick=()=>chooseMember(`${gear.name}を誰に装備する？`,t=>equipMember(t,gear,o.name));modalCard.querySelector('#rogueMaterial').onclick=()=>chooseMember(`${o.name}の力を誰に継承する？`,t=>materialMember(t,o))}
function retireHistorical(o,source='投降'){if(!o||isHinata(o.name)||o.status==='戦利品')return false;const snap={name:o.name,lead:o.lead,war:o.war,int:o.int,pol:o.pol,cha:o.cha};o.force='退場';o.status='戦利品';o.city='';o.loy=0;state.rogue.converted++;log(`${o.name}は${source}後、日向軍の恒久配下にはならず戦利品となった。`);queueReward({type:'officer',officer:snap});return true}
function scrubIllegalRoster(){if(!state?.rogue||state.battle)return;for(const o of [...state.officers])if(o.force==='日向軍'&&!isHinata(o.name))retireHistorical(o,'加入')}
function localHire(actor){const c=state.cities[state.selected];const ts=state.officers.filter(t=>t.city===state.selected&&t.force!=='日向軍'&&t.force!=='退場'&&t.status!=='死亡'&&t.status!=='捕虜');if(!ts.length)return alert('この城に登用・調略できる武将はいません。');showModal(`<h2>登用・調略</h2><div class="choice-list">${ts.map(t=>`<button data-rogue-hire="${t.name}"><b>${t.name}</b> ${isHinata(t.name)?'日向坂メンバー→登用':'歴史武将→戦利品化'}<br><small>${t.force} 忠${t.loy}</small></button>`).join('')}</div><button data-close>閉じる</button>`);modalCard.querySelectorAll('[data-rogue-hire]').forEach(btn=>btn.onclick=()=>{const t=state.officers.find(x=>x.name===btn.dataset.rogueHire);if(!t)return;const chance=clamp(18+(Number(actor.cha)||50)*.5+(100-(Number(t.loy)||70))*.35-(t.status==='君主'?28:0),8,88);c.gold=Math.max(0,c.gold-120);actor.acted=state.turn;const ok=Math.random()*100<chance;closeModal();if(ok){if(isHinata(t.name)){t.force='日向軍';t.city=state.selected;t.status=t.name===state.rulerName?'君主':'一般';t.loy=75;applyStoredStats(t);log(`${actor.name}が${t.name}の登用に成功。`)}else{retireHistorical(t,'調略成功')}}else log(`${actor.name}の${t.name}への${isHinata(t.name)?'登用':'調略'}は失敗。`);render();setTimeout(pumpRewards,100)})}
window.hire=localHire;

if(baseNormalDamage)V39.normalDamage=function(attacker,target,b){const r=baseNormalDamage.apply(this,arguments)||{damage:1,notes:[]};if(!state?.rogue||attacker?.side!=='player'||!isHinata(attacker.name))return r;const m=mods(),type=attacker.type||attacker.apt||'';let mult=1+(m.attack||0);if(type==='騎兵')mult+=m.cavalry||0;if(type==='槍兵')mult+=m.spear||0;if(type==='弩兵')mult+=m.bow||0;if(type==='剣盾兵')mult+=m.shield||0;if(target?.v2436Structure)mult+=m.wall||0;if(Number(attacker.morale)>=80)mult+=m.high||0;if(Number(attacker.morale)<30)mult+=m.low||0;try{const g=window.V2471?.groupOf?.(attacker),links=window.V2471?.linkedAllies?.(b,attacker)||[];if(links.length&&g?.id==='third')mult+=m.third||0;if(links.length&&g?.id==='fifth')mult+=m.fifth||0}catch(e){}if((b?.v2468Objectives||[]).some(o=>o.owner==='player'&&Number(o.x)===Number(attacker.x)&&Number(o.y)===Number(attacker.y)))mult+=m.objective||0;if(state.rogue.finalBossCity&&b?.target===state.rogue.finalBossCity)mult+=m.boss||0;r.damage=Math.max(1,Math.round(Number(r.damage||1)*mult));if(mult>1.001)r.notes=[...(r.notes||[]),'ROGUE強化'];return r};
window.beginBattle=function(){const r=baseBeginBattle.apply(this,arguments);if(state?.rogue&&state.battle){const m=mods();for(const u of state.battle.units||[]){if(u.side!=='player'||!isHinata(u.name)||u.v2436Structure)continue;u.morale=clamp((Number(u.morale)||60)+(m.startMorale||0),0,100);u.moveRangeBonus=(Number(u.moveRangeBonus)||0)+(m.move||0);const commander=state.battle.v2436Commanders?.player===u.name;u.v2470Spirit=clamp(45+(commander?5:0)+(m.startSpirit||0),0,100)}}return r};

function pickCapturedHistorical(snapshot,b){const names=snapshot.filter(u=>u.side==='enemy'&&!u.v2436Structure&&!isHinata(u.name)).map(u=>u.name),xs=names.map(n=>state.officers.find(o=>o.name===n)).filter(Boolean);if(!xs.length)return null;const commander=b?.v2436Commanders?.enemy,ordered=xs.sort((a,c)=>(c.name===commander?1:0)-(a.name===commander?1:0)||((c.lead+c.war+c.int)-(a.lead+a.war+a.int)));const first=ordered[0],base=.55+(mods().captureBonus||0)+(first.name===commander?.toString()?.replace(/^$/,'')?.trim()?.length?0:0);const chance=state.rogue.captures===0?1:clamp(base+(first.name===commander?.toString()?0.15:0),0,0.95);return Math.random()<chance?first:null}
function normalizeHinataAfterCapture(target,enemyNames){for(const name of enemyNames){const o=state.officers.find(x=>x.name===name);if(!o||!isHinata(name)||o.force==='日向軍')continue;o.force='在野';o.status='在野';o.city=target;o.loy=40;log(`${name}は戦後、${target}で在野となった。登用すれば仲間にできる。`)}}
window.endBattle=function(win,retreat){const b=state?.battle,snapshot=b?(b.units||[]).map(u=>({...u})):[],target=b?.target,enemyHinata=snapshot.filter(u=>u.side==='enemy'&&isHinata(u.name)).map(u=>u.name),captured=win&&state?.rogue?pickCapturedHistorical(snapshot,b):null;const r=baseEndBattle.apply(this,arguments);if(!state?.rogue)return r;if(win&&target){normalizeHinataAfterCapture(target,enemyHinata);const c=state.cities[target],m=mods();if(c){if(m.postBattleHeal>0)c.troops+=Math.floor((Number(c.troops)||0)*m.postBattleHeal);if(m.postWall>0)c.wall=Math.min(100,(Number(c.wall)||0)+m.postWall)}if(captured){state.rogue.captures++;retireHistorical(captured,'捕縛')}scrubIllegalRoster();if(state.rogue.finalBossCity===target){state.rogue.finalCleared=true;return endRun(true)}queueUpgrade(`${target}攻略`)}else scrubIllegalRoster();setTimeout(pumpRewards,120);return r};

function frontierBoss(){const own=Object.values(state.cities).filter(c=>c.force==='日向軍'),cand=[];for(const c of own)for(const n of c.n||[]){const e=state.cities[n];if(e?.force&&e.force!=='日向軍'&&!cand.includes(e))cand.push(e)}const xs=cand.length?cand:Object.values(state.cities).filter(c=>c.force&&c.force!=='日向軍');return xs.sort((a,b)=>(Number(b.troops)+Number(b.wall)*55)-(Number(a.troops)+Number(a.wall)*55))[0]||null}
function announceFinalBoss(){if(state.rogue.finalBossCity)return;const b=frontierBoss();if(!b)return;state.rogue.finalBossCity=b.name;log(`最終決戦発生！ 12月中に${b.name}（${b.force}・兵${Math.round(b.troops)}）を攻略せよ。`);setTimeout(()=>{showModal(`<h2>最終決戦：${b.name}</h2><p>${b.force}軍の国境最大戦力が決戦軍を編成した。</p><p><b>12月中に${b.name}を攻略すればランクリア。</b> 月送りすると敗北です。</p><button data-close>出陣準備へ</button>`);},150)}
function economyBonus(){const m=mods();for(const c of Object.values(state.cities).filter(x=>x.force==='日向軍')){if(m.gold)c.gold+=Math.floor((Number(c.commerce)||0)*2.2*m.gold);if(m.food)c.food+=Math.floor((Number(c.farm)||0)*3.5*m.food)}}
window.endMonth=function(){if(!state?.rogue)return baseEndMonth.apply(this,arguments);if(state.rogue.ended)return;if(Number(state.turn)>=12&&state.rogue.finalBossCity&&!state.rogue.finalCleared)return endRun(false);const r=baseEndMonth.apply(this,arguments);economyBonus();if([4,7,10].includes(Number(state.turn)))queueUpgrade(`${state.month}月・成長機会`);if(Number(state.turn)===12)announceFinalBoss();render();setTimeout(pumpRewards,120);return r};

function endRun(win){if(!state?.rogue||state.rogue.ended)return;state.rogue.ended=true;state.rogue.finalCleared=!!win;const cities=Object.values(state.cities).filter(c=>c.force==='日向軍').length,conv=Number(state.rogue.converted)||0,ups=state.rogue.upgrades.length,score=cities*8+conv*6+ups*2+(win?60:0),earned=Math.max(5,Math.floor(score/2)),m=loadMeta();m.total=(Number(m.total)||0)+earned;m.runs=(Number(m.runs)||0)+1;if(win)m.clears=(Number(m.clears)||0)+1;saveMeta(m);state.rogue.meta=m;try{localStorage.removeItem(SAVE_KEY)}catch(e){}app.innerHTML=`<section class="panel rogue-result"><h2>${win?'十二か月戦記 制覇':'十二か月戦記 終了'}</h2><p>${win?'最終決戦を制し、このランをクリアした。':'最終決戦を落とせず、今回の遠征はここまで。'}</p><div class="score">${score} SCORE</div><div class="breakdown"><div>支配城<b>${cities}</b></div><div>武将変換<b>${conv}</b></div><div>ラン強化<b>${ups}</b></div></div><p>陽だまりポイント <b>＋${earned}</b>　累計${m.total}</p><button id="rogueAgain" class="primary">次のランを始める</button></section>`;document.getElementById('rogueAgain').onclick=()=>{state=null;rogueStartScreen()}}

function roguePanel(){if(!state?.rogue||state.battle||state.rogue.ended)return;const dash=document.querySelector('.dashboard'),stack=dash?.querySelector('.stack');if(!stack||document.querySelector('.rogue-panel'))return;const boss=state.rogue.finalBossCity,items=playerHinata().filter(o=>o.rogueEquip).map(o=>`${o.name}：${o.rogueEquip.name}`);stack.insertAdjacentHTML('afterbegin',`<section class="panel rogue-panel"><div class="title">ROGUE・ラン状況</div><div class="rogue-runbox"><div>残り<b>${Math.max(0,12-Number(state.turn)+1)}か月</b></div><div>強化<b>${state.rogue.upgrades.length}</b></div><div>武将変換<b>${state.rogue.converted}</b></div><div>リロール<b>${state.rogue.rerolls}</b></div></div>${boss?`<div class="rogue-final">最終決戦：${boss}を12月中に攻略</div>`:''}<div>${items.length?items.map(x=>`<span class="rogue-chip">${x}</span>`).join(''):'<small>装備なし</small>'}</div><div class="rogue-upgrades">${state.rogue.upgrades.slice(-8).reverse().map(x=>`・${x}`).join('<br>')}</div></section>`);if(boss){const btn=document.querySelector(`[data-city="${boss}"]`);btn?.classList.add('rogue-boss-city')}document.querySelectorAll('.officer').forEach(el=>{const o=playerHinata().find(x=>el.textContent.includes(x.name));if(o?.rogueEquip&&!el.querySelector('.rogue-equip'))el.querySelector('div')?.insertAdjacentHTML('beforeend',`<br><span class="rogue-equip">装備：${o.rogueEquip.name}</span>`)})}
window.render=function(){if(!state)return rogueStartScreen();if(state.rogue?.ended)return; if(state.rogue&&!state.battle)scrubIllegalRoster();const r=baseRender.apply(this,arguments);if(state?.rogue){document.querySelectorAll('.dashboard .panel').forEach(p=>{if(p.textContent.includes('君主 佐々木久美'))p.innerHTML=p.innerHTML.replace('君主 佐々木久美','君主 髙橋未来虹')});setTimeout(roguePanel,30);setTimeout(pumpRewards,90)}return r};
window.startScreen=rogueStartScreen;window.beginGame=()=>{};

document.getElementById('saveBtn').onclick=()=>{if(!state?.rogue||state.rogue.ended)return alert('進行中のランがありません。');localStorage.setItem(SAVE_KEY,JSON.stringify(state));alert('ROGUEランを保存しました。')};
document.getElementById('loadBtn').onclick=()=>{const s=localStorage.getItem(SAVE_KEY);if(!s)return alert('ROGUEのセーブなし');try{state=JSON.parse(s);state.modeId='rogue';state.rogue=state.rogue||{version:1,meta:loadMeta(),mods:initMods(),rewardQueue:[],upgrades:[],upgradeIds:{},items:[],rerolls:0,converted:0,captures:0,deadline:12};state.rogue.rewardQueue=state.rogue.rewardQueue||[];state.rogue.rewardOpen=false;scrubIllegalRoster();render()}catch(e){console.error(e);alert('セーブを読み込めませんでした。')}};
document.getElementById('newBtn').onclick=()=>{if(state?.rogue&&!state.rogue.ended&&!confirm('現在のROGUEランを破棄して新規開始しますか？'))return;state=null;rogueStartScreen()};
rogueStartScreen();
})();