(() => {
"use strict";
const D=window.HQ0,cv=document.getElementById("game"),c=cv.getContext("2d",{alpha:false});c.imageSmoothingEnabled=false;
const $=id=>document.getElementById(id),ui={
 title:$("title"),name:$("name-modal"),nameInput:$("name-input"),dialog:$("dialogue"),portrait:$("portrait"),speaker:$("speaker"),text:$("text"),
 battle:$("battle"),battleLog:$("battle-log"),party:$("party"),commands:$("commands"),menu:$("menu"),menuBody:$("menu-body"),
 load:$("load-modal"),loadSlots:$("load-slots"),clear:$("clear"),clearInfo:$("clear-info"),hud:$("hud"),location:$("location"),
 objective:$("objective"),toast:$("toast"),touch:$("touch")
};
const W=640,H=360,T=32,SAVE="hq0-save-",AUTO="hq0-auto",blocked=new Set([D.TILE.TREE,D.TILE.WATER,D.TILE.WALL]);
const fresh=(name="トシ")=>({version:1,name,map:"grass",x:2,y:5,dir:"right",lv:1,exp:0,hp:66,mp:18,maxHp:66,maxMp:18,atk:13,def:7,gold:25,
 items:{herb:2,sword:0,charm:0},equip:{weapon:null,charm:null},opened:{},defeated:{},visited:{},flags:{tutorial:false,metKumi:false,raid:false,raidWon:false,kumi:false,cave:false,bossIntro:false,boss:false,joined:false,clear:false,fragment:0},
 kumi:{hp:92,mp:24,maxHp:92,maxMp:24,atk:19,def:13},battles:0,steps:0,playTime:0,started:Date.now()});
let s=fresh(),mode="title",titleChoice=0,scene="title",q=[],qi=0,qDone=null,enemies=[],fight=null,tab="status",last=performance.now(),lastMove=0,walk=0,toastTimer,fade=0,fadeDir=0,fadeCb=null,shake=0,flash=0,numbers=[],audio=null;
const keys=new Set();

function show(el,on=true){el.classList.toggle("hidden",!on)}
function setMode(m){mode=m;show(ui.title,m==="title");show(ui.name,m==="name");show(ui.dialog,m==="dialog");show(ui.battle,m==="battle");show(ui.menu,m==="menu");show(ui.load,m==="load");show(ui.clear,m==="clear");show(ui.hud,m==="map");show(ui.touch,m==="map")}
function beep(type="ok"){try{audio||=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume();const o=audio.createOscillator(),g=audio.createGain(),z={ok:[620,.05,"square"],no:[220,.08,"square"],hit:[110,.09,"sawtooth"],heal:[760,.15,"sine"],win:[880,.22,"triangle"],save:[520,.18,"triangle"]}[type]||[620,.05,"square"];o.type=z[2];o.frequency.value=z[0];if(type==="win")o.frequency.exponentialRampToValueAtTime(1350,audio.currentTime+z[1]);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+z[1]);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+z[1])}catch{}}
function toast(text,ms=1800){ui.toast.textContent=text;show(ui.toast);clearTimeout(toastTimer);toastTimer=setTimeout(()=>show(ui.toast,false),ms)}
function time(v){const m=Math.floor(v/60),n=Math.floor(v%60);return`${String(m).padStart(2,"0")}:${String(n).padStart(2,"0")}`}
function objective(){if(!s.flags.tutorial)return"草原の魔物を倒そう";if(!s.flags.metKumi)return"王都北の騎士団長に会おう";if(s.flags.raid&&!s.flags.raidWon)return"東門外の魔物を迎え撃とう";if(!s.flags.boss)return"北の洞窟で異変の原因を探ろう";return"虹色の光を見届けよう"}
function hud(){ui.location.textContent=D.maps[s.map].name;ui.objective.textContent=objective()}
function heroMaxHp(){return s.maxHp+(s.equip.charm==="charm"?10:0)}function heroAtk(){return s.atk+(s.equip.weapon==="sword"?5:0)}function heroDef(){return s.def+(s.equip.charm==="charm"?4:0)}
function serial(){return{...s,playTime:s.playTime+(Date.now()-s.started)/1000,started:Date.now()}}
function save(slot,silent=false){const data=serial();localStorage.setItem(slot==="auto"?AUTO:SAVE+slot,JSON.stringify(data));s.playTime=data.playTime;s.started=Date.now();if(!silent){beep("save");toast(`冒険の書${slot}に記録しました`)}}
function read(slot){try{const v=JSON.parse(localStorage.getItem(slot==="auto"?AUTO:SAVE+slot));return v?.version===1?v:null}catch{return null}}
function load(slot){const v=read(slot);if(!v)return;s={...fresh(v.name),...v,items:{...fresh().items,...v.items},equip:{...fresh().equip,...v.equip},flags:{...fresh().flags,...v.flags},kumi:{...fresh().kumi,...v.kumi},started:Date.now()};s.hp=Math.min(s.hp,heroMaxHp());buildEnemies();scene="map";if(s.flags.clear)showClear();else{setMode("map");hud();fadeIn()}beep("save")}
function autosave(){save("auto",true)}
function fadeTo(cb){if(fadeDir)return;fadeDir=1;fadeCb=cb}function fadeIn(){fade=1;fadeDir=-1}
function changeMap(id,x,y,dir="down"){fadeTo(()=>{s.map=id;s.x=x;s.y=y;s.dir=dir;scene="map";buildEnemies();hud();autosave()})}
function buildEnemies(){enemies=(D.maps[s.map].enemies||[]).filter(e=>{if(s.defeated[e.id])return false;if(e.id==="raid")return s.flags.raid&&!s.flags.raidWon;return!e.hidden}).map(e=>({...e,face:"down"}))}

function replace(lines){return lines.map(([speaker,portrait,text,sc])=>({speaker:speaker==="主人公"?s.name:speaker,portrait,text:text.replaceAll("主人公",s.name),scene:sc}))}
function dialogue(lines,done=null){q=Array.isArray(lines[0])?replace(lines):lines;qi=0;qDone=done;setMode("dialog");dialogLine()}
function dialogLine(){const z=q[qi];if(!z)return endDialog();if(z.scene)scene=z.scene;ui.speaker.textContent=z.speaker;ui.text.textContent=z.text;portrait(z.portrait);beep()}
function advance(){if(mode!=="dialog")return;if(++qi>=q.length)endDialog();else dialogLine()}
function endDialog(){const done=qDone;q=[];qDone=null;if(done)done();else setMode("map")}
function newGame(){s=fresh((ui.nameInput.value.trim()||"トシ").slice(0,8));scene="room";dialogue(D.intro,()=>{scene="map";buildEnemies();setMode("map");hud();fadeIn();autosave();toast("第一章　空色の騎士団長",2600)})}

function delta(dir){return{up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[dir]}
function mapActor(x,y){const e=enemies.find(v=>v.x===x&&v.y===y);if(e)return["enemy",e];const n=D.maps[s.map].npcs.find(v=>v.x===x&&v.y===y);if(n)return["npc",n];const h=D.maps[s.map].chests.find(v=>v.x===x&&v.y===y&&!s.opened[v.id]);if(h)return["chest",h];return null}
function canWalk(x,y){const m=D.maps[s.map];if(x<0||y<0||x>=20||y>=11||blocked.has(m.tiles[y][x]))return false;return!mapActor(x,y)}
function move(dir){
 if(mode!=="map"||fadeDir)return;s.dir=dir;const[dx,dy]=delta(dir),x=s.x+dx,y=s.y+dy,a=mapActor(x,y);
 if(a?.[0]==="enemy"){meetEnemy(a[1],false);return}
 if(s.map==="cave"&&s.x===10&&s.y===9&&dir==="down"){changeMap("grass",10,1,"down");return}
 if(s.map==="grass"&&x===10&&y===0&&!s.flags.cave){toast("洞窟の入口は固く閉ざされている");beep("no");return}
 if(!canWalk(x,y)){beep("no");return}s.x=x;s.y=y;s.steps++;walk++;checkWarp();if(mode==="map")chase()
}
function checkWarp(){if(s.map==="grass"&&s.x===19&&s.y===5){if(!s.flags.tutorial){s.x=18;toast("魔物を放置して王都へは行けない")}else changeMap("city",10,9,"up")}else if(s.map==="city"&&s.x===10&&s.y===10)changeMap("grass",18,5,"left");else if(s.map==="grass"&&s.x===10&&s.y===0&&s.flags.cave)changeMap("cave",10,9,"up")}
function chase(){const occupied=new Set(enemies.map(e=>`${e.x},${e.y}`));for(const e of enemies){if(e.boss)continue;const dist=Math.abs(e.x-s.x)+Math.abs(e.y-s.y);if(dist<1||dist>4)continue;let dx=0,dy=0;if(Math.abs(e.x-s.x)>=Math.abs(e.y-s.y))dx=Math.sign(s.x-e.x);else dy=Math.sign(s.y-e.y);const x=e.x+dx,y=e.y+dy;e.face=dx<0?"left":dx>0?"right":dy<0?"up":"down";if(x===s.x&&y===s.y){meetEnemy(e,true);return}if(canWalk(x,y)&&!occupied.has(`${x},${y}`)){occupied.delete(`${e.x},${e.y}`);e.x=x;e.y=y;occupied.add(`${x},${y}`)}}}
function interact(){if(mode==="dialog")return advance();if(mode!=="map")return;const[dx,dy]=delta(s.dir),a=mapActor(s.x+dx,s.y+dy);if(!a){beep("no");return}if(a[0]==="npc")talk(a[1]);else if(a[0]==="chest")chest(a[1]);else meetEnemy(a[1],false)}
function talk(n){if(n.special==="kumi"){if(s.flags.metKumi)return dialogue([["佐々木久美","kumi",s.flags.cave?"北の洞窟へ行こう。嫌な気配が強くなってる。":"東門の外へ急ぐよ！"]]);s.flags.metKumi=true;dialogue(D.meet,()=>{s.flags.raid=true;s.flags.kumi=true;s.map="grass";s.x=15;s.y=5;s.dir="right";scene="map";buildEnemies();setMode("map");hud();fadeIn();autosave();toast("久美と共闘して住民を守れ！")});return}dialogue(n.lines.map(t=>({speaker:n.name,portrait:n.type,text:t})),n.shop?shop:null)}
function chest(h){s.opened[h.id]=true;s.items[h.item]=(s.items[h.item]||0)+h.amount;beep("win");dialogue([{speaker:"SYSTEM",portrait:h.item==="charm"?"light":"chest",text:h.text}],()=>{setMode("map");autosave()})}
function shop(){setMode("menu");ui.menu.querySelector("nav").classList.add("hidden");ui.menuBody.innerHTML=`<div class="list"><div class="item"><div><strong>薬草</strong><span>HP35回復 / 15G</span></div><button data-buy="herb">買う</button></div><div class="item"><div><strong>青銅の剣</strong><span>攻撃+5 / 45G</span></div><button data-buy="sword"${s.items.sword?" disabled":""}>買う</button></div><div class="card"><strong>所持金 ${s.gold}G</strong><span>×で買い物を終えます。</span></div></div>`;ui.menuBody.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>{const id=b.dataset.buy,price=id==="herb"?15:45;if(s.gold<price)return toast("ゴールドが足りない");s.gold-=price;s.items[id]=(s.items[id]||0)+1;beep("save");toast(`${id==="herb"?"薬草":"青銅の剣"}を買った`);shop()})}

function meetEnemy(e,ambush){if(e.boss&&!s.flags.bossIntro){s.flags.bossIntro=true;dialogue(D.bossIntro,()=>startBattle(e,false));return}startBattle(e,ambush)}
function party(){const a=[{id:"hero",name:s.name,hp:s.hp,mp:s.mp,maxHp:heroMaxHp(),maxMp:s.maxMp,atk:heroAtk(),def:heroDef(),guard:false,buff:0}];if(s.flags.kumi||s.flags.joined)a.push({id:"kumi",name:"久美",hp:s.kumi.hp,mp:s.kumi.mp,maxHp:s.kumi.maxHp,maxMp:s.kumi.maxMp,atk:s.kumi.atk,def:s.kumi.def,guard:false,buff:0});return a}
function sync(){if(!fight)return;const h=fight.party[0];s.hp=h.hp;s.mp=h.mp;const k=fight.party.find(v=>v.id==="kumi");if(k){s.kumi.hp=k.hp;s.kumi.mp=k.mp}}
function startBattle(src,ambush=false){const base=D.enemies[src.kind];fight={src,foe:{...base,kind:src.kind,maxHp:base.hp},party:party(),actor:0,turn:1,captain:0,busy:true};s.battles++;scene="battle";setMode("battle");ui.battleLog.textContent=ambush?`${base.name}に背後を取られた！`:`${base.name}が立ちはだかった！`;battleUi();flash=.6;setTimeout(()=>ambush?enemyTurn():actorTurn(),650)}
function battleUi(){if(!fight)return;ui.party.innerHTML=fight.party.map(p=>`<div class="member"><div><span>${p.name}</span><span>HP ${p.hp}/${p.maxHp}</span></div><div class="bar"><i style="width:${100*p.hp/p.maxHp}%"></i></div><div><span>MP</span><span>${p.mp}/${p.maxMp}</span></div><div class="bar mp"><i style="width:${100*p.mp/p.maxMp}%"></i></div></div>`).join("")}
function actorTurn(){if(!fight)return;fight.busy=false;while(fight.actor<fight.party.length&&fight.party[fight.actor].hp<=0)fight.actor++;if(fight.actor>=fight.party.length)return enemyTurn();const p=fight.party[fight.actor];ui.battleLog.textContent=`${p.name}の行動を選んでください。`;battleUi();commands("root")}
function commands(level){const p=fight?.party[fight.actor];if(!p||fight.busy)return;fight.commandLevel=level;fight.commandChoice=0;let list=[];if(level==="root"){list=[["たたかう",attack],["スキル",()=>commands("skill")],["アイテム",()=>commands("item")],["ぼうぎょ",guard]];if(!fight.foe.boss)list.push(["にげる",escapeBattle])}else if(level==="skill"){list=p.id==="hero"?[["推しの声援 MP3",cheer,p.mp<3||fight.party.length<2],["オーラブレード MP4",aura,p.mp<4],["もどる",()=>commands("root")]]:[["キャプテンコール MP4",captain,p.mp<4],["蒼天突き MP5",thrust,p.mp<5],["もどる",()=>commands("root")]]}else{for(const z of fight.party)list.push([`薬草→${z.name} ×${s.items.herb}`,()=>herb(z),!s.items.herb||z.hp<=0||z.hp>=z.maxHp]);list.push(["もどる",()=>commands("root")])}ui.commands.innerHTML="";for(const[label,fn,disabled]of list){const b=document.createElement("button");b.textContent=label;b.disabled=!!disabled;b.onclick=()=>{if(fight?.busy||b.disabled)return;beep();fn()};ui.commands.appendChild(b)}focusBattle(0)}
function focusBattle(delta){if(!fight)return;const list=[...ui.commands.querySelectorAll("button:not(:disabled)")];if(!list.length)return;fight.commandChoice=(fight.commandChoice+delta+list.length)%list.length;list.forEach((b,i)=>b.classList.toggle("selected",i===fight.commandChoice));list[fight.commandChoice].focus()}
function damage(atk,def,m=1){return Math.max(1,Math.floor((atk*m-def*.55)*(.9+Math.random()*.2)))}
function hit(target,n,color="#fff0a0"){beep("hit");shake=5;const p=target==="foe"?[480,105]:target==="hero"?[145,175]:[240,175];numbers.push({text:String(n),x:p[0],y:p[1],life:1,color})}
function attack(){const p=fight.party[fight.actor],n=damage(p.atk+p.buff,fight.foe.def);fight.busy=true;fight.foe.hp=Math.max(0,fight.foe.hp-n);ui.battleLog.textContent=`${p.name}の攻撃！\n${fight.foe.name}に ${n} ダメージ！`;hit("foe",n);afterAction()}
function cheer(){const p=fight.party[fight.actor],k=fight.party.find(v=>v.id==="kumi");fight.busy=true;p.mp-=3;k.buff=Math.max(k.buff,7);ui.battleLog.textContent=`${p.name}の「推しの声援」！\n久美の攻撃力が上がった！`;beep("heal");afterAction(700)}
function aura(){const p=fight.party[fight.actor],n=damage(p.atk+p.buff+7,fight.foe.def,1.4);fight.busy=true;p.mp-=4;fight.foe.hp=Math.max(0,fight.foe.hp-n);ui.battleLog.textContent=`${p.name}の「オーラブレード」！\n空色の光が ${n} ダメージ！`;flash=.5;hit("foe",n,"#9cf3ff");afterAction(750)}
function captain(){const p=fight.party[fight.actor];fight.busy=true;p.mp-=4;fight.captain=3;fight.party.forEach(v=>v.buff=Math.max(v.buff,4));ui.battleLog.textContent="久美の「キャプテンコール」！\n味方全員の攻撃と守りが上がった！";beep("win");flash=.35;afterAction(850)}
function thrust(){const p=fight.party[fight.actor],n=damage(p.atk+p.buff+9,fight.foe.def,1.55);fight.busy=true;p.mp-=5;fight.foe.hp=Math.max(0,fight.foe.hp-n);ui.battleLog.textContent=`久美の「蒼天突き」！\n${fight.foe.name}に ${n} ダメージ！`;hit("foe",n,"#ffe074");afterAction(750)}
function herb(target){const p=fight.party[fight.actor],n=Math.min(35,target.maxHp-target.hp);fight.busy=true;s.items.herb--;target.hp+=n;ui.battleLog.textContent=`${p.name}は薬草を使った。\n${target.name}のHPが ${n} 回復！`;beep("heal");numbers.push({text:`+${n}`,x:target.id==="hero"?145:240,y:175,life:1,color:"#8ff0a4"});afterAction(650)}
function guard(){const p=fight.party[fight.actor];fight.busy=true;p.guard=true;ui.battleLog.textContent=`${p.name}は身を守っている。`;afterAction(500)}
function afterAction(ms=600){sync();battleUi();setTimeout(()=>{if(!fight)return;if(fight.foe.hp<=0)return victory();fight.actor++;actorTurn()},ms)}
function escapeBattle(){fight.busy=true;if(Math.random()<.75){ui.battleLog.textContent="うまく逃げ切った！";setTimeout(()=>exitBattle(),650)}else{ui.battleLog.textContent="逃げられなかった！";setTimeout(enemyTurn,650)}}
function enemyMove(){const f=fight.foe;if(f.kind==="boss"){const z=fight.turn%4;if(z===2)return["不安の霧","debuff",0];if(z===3)return["笑顔吸収","drain",1.05];if(z===0)return["暗黒のつぶやき","all",.82];return["ため息","one",1]}if(f.kind==="bat"&&fight.turn%3===0)return["眠たい羽音","all",.65];return[f.kind==="slime"?"しょんぼり泡":f.kind==="hound"?"不安の遠吠え":"錆びた剣","one",1]}
function hurt(p,pow){const n=Math.max(1,Math.floor(damage(fight.foe.atk,p.def,pow)*(fight.captain?0.58:1)*(p.guard?.48:1)));p.hp=Math.max(0,p.hp-n);hit(p.id,n,"#ff9c9c");return n}
function enemyTurn(){if(!fight)return;fight.busy=true;ui.commands.innerHTML="";const alive=fight.party.filter(p=>p.hp>0);if(!alive.length)return defeat();const[name,type,pow]=enemyMove(),targets=type==="all"?alive:[alive[Math.floor(Math.random()*alive.length)]];let log=`${fight.foe.name}の「${name}」！`;if(type==="debuff"){fight.party.forEach(p=>p.buff=Math.min(p.buff,-3));log+="\n不安の霧で味方の攻撃力が下がった！";flash=.3}else if(type==="drain"){const n=hurt(targets[0],pow);fight.foe.hp=Math.min(fight.foe.maxHp,fight.foe.hp+Math.ceil(n/2));log+=`\n${targets[0].name}から笑顔を吸収！ ${n}ダメージ。`}else log+="\n"+targets.map(p=>`${p.name}に ${hurt(p,pow)}ダメージ`).join("、")+"！";ui.battleLog.textContent=log;sync();battleUi();setTimeout(()=>{if(!fight)return;if(!fight.party.some(p=>p.hp>0))return defeat();fight.turn++;fight.actor=0;fight.captain=Math.max(0,fight.captain-1);fight.party.forEach(p=>{p.guard=false;if(p.buff>0)p.buff--});actorTurn()},1000)}
function victory(){const id=fight.src.id,f=fight.foe;s.defeated[id]=true;s.gold+=f.gold;s.exp+=f.exp;sync();let up="";while(s.exp>=s.lv*40){s.exp-=s.lv*40;s.lv++;s.maxHp+=9;s.maxMp+=3;s.atk+=3;s.def+=2;s.hp=heroMaxHp();s.mp=s.maxMp;up+=`\n${s.name}はレベル${s.lv}になった！`}ui.battleLog.textContent=`${f.name}を倒した！\n${f.exp}EXPと${f.gold}Gを獲得。${up}`;beep("win");flash=.5;battleUi();setTimeout(()=>exitBattle(()=>storyWin(id)),1400)}
function exitBattle(done){fight=null;scene="map";buildEnemies();setMode("map");hud();if(done)done()}
function storyWin(id){if(id==="tutorial"){s.flags.tutorial=true;toast("王都ソラシドへの道が開いた！");autosave()}else if(id==="raid"){s.flags.raidWon=true;s.flags.raid=false;s.flags.cave=true;dialogue(D.afterRaid,()=>{s.x=10;s.y=1;s.dir="up";scene="map";setMode("map");hud();autosave();toast("久美がゲスト加入した！")})}else if(id==="boss"){s.flags.boss=true;s.flags.joined=true;s.flags.kumi=false;s.flags.fragment=1;s.flags.clear=true;dialogue(D.ending,()=>{scene="ending";showClear();autosave()})}else autosave()}
function defeat(){ui.battleLog.textContent="力尽きてしまった……。\n王都の騎士たちに助けられ、所持金が半分になった。";s.gold=Math.floor(s.gold/2);s.hp=heroMaxHp();s.mp=s.maxMp;s.kumi.hp=s.kumi.maxHp;s.kumi.mp=s.kumi.maxMp;setTimeout(()=>{fight=null;scene="map";s.map=s.flags.metKumi?"city":"grass";s.x=s.flags.metKumi?10:2;s.y=s.flags.metKumi?9:5;buildEnemies();setMode("map");hud();autosave();fadeIn()},1700)}

function openMenu(which="status"){if(mode!=="map")return;tab=which;setMode("menu");ui.menu.querySelector("nav").classList.remove("hidden");menu()}
function closeMenu(){if(mode!=="menu")return;ui.menu.querySelector("nav").classList.remove("hidden");setMode("map");hud();beep("no")}
function menu(){ui.menu.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("selected",b.dataset.tab===tab));if(tab==="status")ui.menuBody.innerHTML=`<div class="cards"><div class="card"><strong>${s.name} Lv.${s.lv}</strong><span>オーラナイト</span></div><div class="card"><strong>HP ${s.hp}/${heroMaxHp()}</strong><span>MP ${s.mp}/${s.maxMp}</span></div><div class="card"><strong>攻撃 ${heroAtk()} / 守備 ${heroDef()}</strong><span>次のLvまで ${s.lv*40-s.exp}EXP</span></div><div class="card"><strong>${s.gold}G</strong><span>欠片 ${s.flags.fragment}/7</span></div>${s.flags.kumi||s.flags.joined?`<div class="card"><strong>佐々木久美 Lv.3</strong><span>コマンダー / HP ${s.kumi.hp}/${s.kumi.maxHp}</span></div><div class="card"><strong>キャプテンコール</strong><span>味方全体を強化</span></div>`:`<div class="card"><strong>仲間</strong><span>まだ誰もいない</span></div>`}</div>`;
 else if(tab==="items"){ui.menuBody.innerHTML=`<div class="list"><div class="item"><div><strong>薬草 ×${s.items.herb}</strong><span>味方のHPを35回復</span></div><button id="use-herb"${!s.items.herb||s.hp>=heroMaxHp()?" disabled":""}>使う</button></div><div class="item"><div><strong>ハッピーオーラの欠片 ×${s.flags.fragment}</strong><span>温かな虹色の光</span></div></div></div>`;$("use-herb")?.addEventListener("click",()=>{s.items.herb--;s.hp=Math.min(heroMaxHp(),s.hp+35);beep("heal");toast("薬草でHPが回復した");menu()})}
 else if(tab==="equip"){ui.menuBody.innerHTML=`<div class="list"><div class="item"><div><strong>武器：${s.equip.weapon==="sword"?"青銅の剣":"旅人の剣"}</strong><span>現在の攻撃力 ${heroAtk()}</span></div><button data-equip="sword"${!s.items.sword?" disabled":""}>${s.equip.weapon==="sword"?"外す":"装備"}</button></div><div class="item"><div><strong>装飾：${s.equip.charm==="charm"?"空色のお守り":"なし"}</strong><span>現在の守備力 ${heroDef()}</span></div><button data-equip="charm"${!s.items.charm?" disabled":""}>${s.equip.charm==="charm"?"外す":"装備"}</button></div></div>`;ui.menuBody.querySelectorAll("[data-equip]").forEach(b=>b.onclick=()=>{const id=b.dataset.equip,slot=id==="sword"?"weapon":"charm",before=heroMaxHp();s.equip[slot]=s.equip[slot]===id?null:id;if(heroMaxHp()>before)s.hp+=heroMaxHp()-before;s.hp=Math.min(s.hp,heroMaxHp());beep("save");menu()})}
 else{ui.menuBody.innerHTML=`<div class="list">${[1,2,3].map(n=>{const v=read(n);return`<div class="slot ${v?"":"empty"}"><div><strong>冒険の書 ${n}</strong><span>${v?`${v.name} Lv.${v.lv} / ${D.maps[v.map].name} / ${time(v.playTime||0)}`:"記録はありません"}</span></div><button data-save="${n}">記録</button></div>`}).join("")}</div>`;ui.menuBody.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>{save(+b.dataset.save);menu()})}}
function loadSlots(){ui.loadSlots.innerHTML=["auto",1,2,3].map(n=>{const v=read(n),label=n==="auto"?"オートセーブ":`冒険の書 ${n}`;return`<div class="slot ${v?"":"empty"}"><div><strong>${label}</strong><span>${v?`${v.name} Lv.${v.lv} / ${D.maps[v.map].name} / ${time(v.playTime||0)}`:"記録はありません"}</span></div><button data-load="${n}"${v?"":" disabled"}>ロード</button></div>`}).join("");ui.loadSlots.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>load(b.dataset.load))}
function showClear(){setMode("clear");ui.clearInfo.textContent=`主人公 Lv.${s.lv}　戦闘 ${s.battles}回　${time(s.playTime+(Date.now()-s.started)/1000)}`;beep("win")}
function title(){fight=null;scene="title";setMode("title");titleChoice=0;titleButtons();fadeIn()}function titleButtons(){document.querySelectorAll("[data-title]").forEach((b,i)=>b.classList.toggle("selected",i===titleChoice))}

function bind(){
 document.querySelectorAll("[data-title]").forEach((b,i)=>{b.onmouseenter=()=>{titleChoice=i;titleButtons()};b.onclick=()=>{beep();if(b.dataset.title==="new"){setMode("name");setTimeout(()=>ui.nameInput.focus(),20)}else{loadSlots();setMode("load")}}});
 $("name-ok").onclick=newGame;$("name-back").onclick=()=>setMode("title");$("menu-close").onclick=closeMenu;$("load-back").onclick=()=>setMode("title");$("clear-save").onclick=()=>save(1);$("clear-title").onclick=title;ui.dialog.onclick=advance;
 document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;beep();menu()});
 document.querySelectorAll("[data-dir]").forEach(b=>b.onpointerdown=e=>{e.preventDefault();move(b.dataset.dir)});$("touch-a").onpointerdown=e=>{e.preventDefault();confirmKey()};$("touch-b").onpointerdown=e=>{e.preventDefault();cancelKey()};$("touch-menu").onpointerdown=e=>{e.preventDefault();openMenu()};
 addEventListener("keydown",e=>{const k=e.key.toLowerCase();if(["arrowup","arrowdown","arrowleft","arrowright"," ","enter"].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(mode==="title"){if(["arrowup","w","arrowdown","s"].includes(k)){titleChoice=titleChoice?0:1;titleButtons();beep()}else if(["enter","z"," "].includes(k))document.querySelector(`[data-title="${titleChoice?"load":"new"}"]`).click();return}if(mode==="battle"){if(["arrowup","arrowleft","w","a"].includes(k))focusBattle(-1);else if(["arrowdown","arrowright","s","d"].includes(k))focusBattle(1);else if(["enter","z"," "].includes(k)){const list=[...ui.commands.querySelectorAll("button:not(:disabled)")];list[fight?.commandChoice||0]?.click()}else if(["escape","x"].includes(k))commands("root");return}if(mode==="name"&&k==="enter")newGame();else if(["enter","z"," "].includes(k))confirmKey();else if(["escape","x","m"].includes(k))cancelKey();else if(mode==="map"){const d=keyDir(k);if(d)move(d)}});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));addEventListener("blur",()=>keys.clear())
}
function confirmKey(){if(mode==="dialog")advance();else if(mode==="map")interact()}function cancelKey(){if(mode==="map")openMenu();else if(mode==="menu")closeMenu();else if(mode==="load"||mode==="name")setMode("title")}
function keyDir(k){if(k==="arrowup"||k==="w")return"up";if(k==="arrowdown"||k==="s")return"down";if(k==="arrowleft"||k==="a")return"left";if(k==="arrowright"||k==="d")return"right"}

function rect(x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function renderTitle(now){rect(0,0,W,80,"#4fc4e5");rect(0,80,W,90,"#83dce8");rect(0,170,W,190,"#28654f");for(let i=0;i<25;i++)rect((i*83)%W,18+(i*37)%115,3,2,"#f5ffff");cloud(55,52,1);cloud(480,38,1.1);mountain(0,130,220,"#4b91a2");mountain(185,120,260,"#3c7f91");mountain(420,135,220,"#4a8998");rect(0,280,W,80,"#215345");castle(270,130,1);character("hero",205,248,"right",Math.floor(now/600)%2,2);character("kumi",372,245,"left",Math.floor(now/600)%2,2);for(let i=0;i<5;i++){const a=now/900+i*1.25;rect(320+Math.cos(a)*(65+i*2),220+Math.sin(a)*18,4,4,["#ff91a5","#ffda6c","#7ce3b4","#73d8ef","#c29ced"][i])}}
function cloud(x,y,s){rect(x+12*s,y,44*s,9*s,"#efffff");rect(x,y+8*s,75*s,11*s,"#efffff");rect(x+22*s,y-6*s,28*s,8*s,"#efffff");rect(x+6*s,y+19*s,58*s,4*s,"#bce9ef")}
function mountain(x,y,w,col){for(let i=0;i<9;i++){const q=w*(1-i/9);rect(x+(w-q)/2,y+i*13,q,14,i%2?col:"#65a5af")}rect(x+w*.45,y+8,w*.1,28,"#d8f3f1")}
function castle(x,y,s){rect(x+14*s,y+20*s,76*s,100*s,"#e5eeed");rect(x,y+50*s,28*s,70*s,"#c8dce0");rect(x+76*s,y+50*s,28*s,70*s,"#c8dce0");rect(x+37*s,y,31*s,120*s,"#f4f7f4");rect(x+37*s,y-14*s,31*s,15*s,"#2a87aa");rect(x+47*s,y+78*s,13*s,42*s,"#193c58");rect(x+48*s,y+20*s,9*s,16*s,"#4ca0b9");rect(x+52*s,y-32*s,2*s,20*s,"#f0cf6b");rect(x+54*s,y-31*s,17*s,9*s,"#57c8e5")}
function cinematic(sc,now){if(sc==="room"||sc==="glow"){rect(0,0,W,H,"#11162a");rect(0,230,W,130,"#503a36");rect(42,60,150,120,"#253052");rect(50,68,134,103,"#3c80a4");castle(93,94,.36);rect(230,164,262,20,"#6a4a3c");rect(292,108,126,72,"#07131f");rect(299,115,112,58,sc==="glow"?"#e5feff":"#55b9d5");character("hero",324,193,"up",0,2.2);if(sc==="glow"){c.fillStyle=`rgba(195,248,255,${.3+(Math.sin(now/180)+1)*.18})`;c.fillRect(230,58,262,220)}}else if(sc==="warp"){rect(0,0,W,H,"#07142d");for(let i=0;i<55;i++){const a=i*.71+now/850,r=(i*19+now/8)%240+6;rect(W/2+Math.cos(a)*r,H/2+Math.sin(a)*r*.58,3+i%3,3+i%3,["#70d8f2","#f6d66f","#b998ed"][i%3])}character("hero",304,150,"down",Math.floor(now/200)%2,2)}else renderWorld(now)}
function tile(type,x,y,wx,wy){const z=D.TILE;if(type===z.GRASS||type===z.FLOWER){rect(x,y,32,32,"#3b8f65");rect(x,y+24,32,8,"#327a58");rect(x+5+(wx*7+wy*3)%20,y+8,2,5,"#75bb76");if(type===z.FLOWER){rect(x+8,y+10,3,3,"#ffd86b");rect(x+21,y+19,3,3,"#f39aaa")}}else if(type===z.PATH){rect(x,y,32,32,"#b9a471");rect(x,y+25,32,7,"#aa9361");rect(x+(wx*7)%22,y+(wy*9)%21,4,2,"#d8c68e");rect(x+21,y+8,3,3,"#8d7954")}else if(type===z.TREE){rect(x,y,32,32,"#214e46");rect(x+13,y+20,7,12,"#684f38");rect(x+4,y+3,24,20,"#286650");rect(x+8,y,14,9,"#3b805a");rect(x+2,y+12,9,8,"#1c5647")}else if(type===z.WATER){rect(x,y,32,32,"#2e89b2");rect(x,y+8,17,3,"#68c5dc");rect(x+12,y+21,20,3,"#1e719d")}else if(type===z.BRIDGE){rect(x,y,32,32,"#2d89b2");for(let i=0;i<4;i++)rect(x+i*8,y+1,7,30,i%2?"#8f6744":"#a8794e");rect(x,y+5,32,2,"#4d382b");rect(x,y+25,32,2,"#4d382b")}else if(type===z.FLOOR){rect(x,y,32,32,"#d3c59d");rect(x,y+30,32,2,"#9d8c68");rect(x+15,y,2,32,"#b5a680")}else if(type===z.WALL){rect(x,y,32,32,"#68757d");rect(x+3,y+4,26,25,"#879398");rect(x,y+15,32,2,"#4c5963");rect(x+(wy%2?16:0),y,2,15,"#4c5963")}else if(type===z.STONE){rect(x,y,32,32,"#263142");rect(x+2,y+3,28,26,"#354153");rect(x+5,y+6,18,4,"#48566a");rect(x,y+28,32,4,"#171e2b")}else if(type===z.CAVE){rect(x,y,32,32,"#53636b");rect(x+2,y+4,28,28,"#29333c");rect(x+7,y+9,18,23,"#070c13")}else{rect(x,y,32,32,"#273245");rect(x+13,y+3,7,20,"#79e6ec");rect(x+9,y+10,5,15,"#42a8c5");rect(x+18,y+12,6,13,"#bcf8f2");rect(x+6,y+25,21,5,"#17202e")}}
function renderWorld(now){const m=D.maps[s.map];for(let y=0;y<11;y++)for(let x=0;x<20;x++)tile(m.tiles[y][x],x*T,y*T,x,y);m.chests.filter(h=>!s.opened[h.id]).forEach(h=>drawChest(h.x*T,h.y*T));m.npcs.forEach(n=>character(n.type,n.x*T,n.y*T,"down",Math.floor(now/650)%2));enemies.forEach(e=>monster(e.kind,e.x*T,e.y*T,now));character("hero",s.x*T,s.y*T,s.dir,walk%2);if(s.flags.kumi||s.flags.joined){const[dx,dy]=delta(s.dir==="left"?"right":s.dir==="right"?"left":s.dir==="up"?"down":"up"),x=s.x+dx,y=s.y+dy;if(canWalk(x,y))character("kumi",x*T,y*T,s.dir,walk%2)}}
function character(type,x,y,dir="down",frame=0,scale=1){const p=(a,b,w,h,col)=>rect(x+a*scale,y+b*scale,w*scale,h*scale,col),P={hero:["#2b2934","#171722","#f0c6a1","#1e5f89","#70d9ef","#efd36d"],kumi:["#583b31","#34241f","#f1c7a5","#e8f4f3","#58bddf","#e7c866"],guard:["#4c4034","#27231e","#eabf9a","#aab7c0","#2f7397","#e5c55d"],elder:["#d9dee1","#a7b1b7","#ddb28f","#786b9a","#a9d9d8","#e5c55d"],child:["#49352e","#2a211e","#f0c5a2","#f0d77f","#61c8e3","#f5f1cf"],merchant:["#996a3b","#5d4028","#eab98d","#9b5b42","#d8a85d","#f2d67a"],wisp:["#c5f6f0","#73dadd","#e8ffff","#5ba8ca","#c7ffff","#f5dc74"]}[type]||["#39323b","#201d24","#ecc39f","#416e88","#70d7e8","#e4c85e"],b=frame?1:0;if(type==="wisp"){p(11,4+b,10,6,P[4]);p(7,9+b,18,13,P[1]);p(10,11+b,12,9,P[2]);p(8,22+b,16,7,P[3]);p(12,29+b,8,3,P[4]);return}p(9,3+b,14,8,P[0]);p(8,8+b,16,10,P[0]);p(10,9+b,12,10,P[2]);if(dir!=="up"){p(13,12+b,2,2,"#292332");p(18,12+b,2,2,"#292332");p(14,16+b,5,1,"#c77f75")}else p(10,10+b,12,9,P[1]);if(type==="kumi"){p(7,8+b,4,15,P[1]);p(21,8+b,4,15,P[1])}p(8,19+b,16,8,P[3]);p(7,21+b,4,7,P[2]);p(21,21+b,4,7,P[2]);p(9,20+b,14,3,P[4]);p(10,25+b,12,2,P[5]);p(10-(frame?1:0),27+b,5,5-b,P[1]);p(17+(frame?1:0),27+b,5,5-b,P[1]);if(type==="hero"){p(23,18+b,2,11,"#d7e2e0");p(25,17+b,2,7,P[5])}if(type==="kumi"){p(5,12+b,2,17,"#d9e7e7");p(4,7+b,4,6,P[5])}if(type==="child"){p(8,3+b,16,4,P[4]);p(11,b,10,4,P[4])}}
function drawChest(x,y){rect(x+5,y+10,22,17,"#6f4527");rect(x+7,y+6,18,8,"#b97831");rect(x+5,y+13,22,4,"#e1ae4e");rect(x+14,y+14,5,7,"#f5df78");rect(x+7,y+25,18,3,"#3b291f")}
function monster(kind,x,y,now){const b=Math.floor(now/330)%2;if(kind==="slime"){rect(x+7,y+13-b,18,13,"#52bad4");rect(x+10,y+8-b,12,8,"#6dd8e7");rect(x+11,y+16-b,3,3,"#152638");rect(x+19,y+16-b,3,3,"#152638");rect(x+14,y+22-b,5,2,"#2a6073")}else if(kind==="bat"){rect(x+12,y+10+b,9,13,"#735aa8");rect(x+2,y+8+b,11,6,"#594584");rect(x+20,y+8+b,11,6,"#594584");rect(x+8,y+5+b,5,5,"#8e72bb");rect(x+21,y+5+b,5,5,"#8e72bb");rect(x+14,y+13+b,2,2,"#f08791");rect(x+19,y+13+b,2,2,"#f08791")}else if(kind==="hound"){rect(x+6,y+13+b,20,11,"#454c62");rect(x+18,y+8+b,10,10,"#5a6178");rect(x+19,y+4+b,4,6,"#3a4055");rect(x+25,y+5+b,4,6,"#3a4055");rect(x+24,y+11+b,2,2,"#f57a89");rect(x+8,y+23+b,4,7,"#303747");rect(x+21,y+23+b,4,7,"#303747")}else if(kind==="armor"){rect(x+9,y+5+b,15,8,"#7c8b99");rect(x+7,y+12+b,19,15,"#596977");rect(x+11,y+9+b,11,2,"#1c2631");rect(x+14,y+9+b,3,2,"#e76878");rect(x+5,y+16+b,4,11,"#8998a1");rect(x+24,y+16+b,4,11,"#8998a1")}else{rect(x+6,y+7+b,20,21,"#332648");rect(x+10,y+3+b,5,7,"#553c6c");rect(x+20,y+3+b,5,7,"#553c6c");rect(x+11,y+13+b,3,3,"#f05b83");rect(x+20,y+13+b,3,3,"#f05b83");rect(x+14,y+21+b,8,3,"#110e1d")}}
function portrait(type){const p=ui.portrait.getContext("2d");p.imageSmoothingEnabled=false;const r=(x,y,w,h,col)=>{p.fillStyle=col;p.fillRect(x,y,w,h)};r(0,0,84,84,type==="boss"?"#271d3e":"#6fcbe1");if(type==="boss"){r(12,24,60,60,"#21192f");r(20,8,15,23,"#624675");r(52,8,15,23,"#624675");r(26,38,8,7,"#fa6389");r(52,38,8,7,"#fa6389");r(31,59,25,7,"#090812");return}if(type==="light"||type==="chest"){for(let i=0;i<7;i++)r(38-i*3,11+i*8,9+i*6,6,["#ff9bac","#ffdd74","#86e7bd","#7adcf2","#c6a1f0"][i%5]);r(35,30,14,24,"#f8ffff");return}const k=type==="kumi",hair=k?"#53382f":type==="guard"?"#6d5a47":type==="elder"?"#d1d8dc":type==="child"?"#49352e":type==="merchant"?"#9a693b":"#2c2933",dark=k?"#34241f":type==="elder"?"#9aa8ad":"#1a1920",skin=type==="elder"?"#ddb38e":"#f0c7a5",cloth=k?"#e7f4f3":type==="guard"?"#9fafba":type==="child"?"#f0d47b":"#245f87",accent=k?"#58bddf":type==="child"?"#60c9e3":"#71d9ef";r(17,9,52,29,hair);r(11,26,15,43,dark);r(58,25,15,45,dark);r(22,24,42,39,skin);r(18,15,48,14,hair);r(27,38,5,5,"#2b2630");r(52,38,5,5,"#2b2630");r(37,53,12,3,"#c87872");r(17,62,51,22,cloth);r(22,64,42,7,accent);if(k){r(14,10,10,24,dark);r(61,10,10,24,dark)}}
function renderBattle(now){const cave=s.map==="cave";rect(0,0,W,H,cave?"#16182a":"#72cada");if(cave){for(let y=0;y<230;y+=32)for(let x=0;x<W;x+=48){rect(x+(y/32%2)*18,y,44,28,"#242d3d");rect(x+4+(y/32%2)*18,y+4,36,4,"#354153")}rect(0,228,W,132,"#262438")}else{rect(0,0,W,120,"#70cce0");cloud(40,45,.75);cloud(480,28,.8);rect(0,120,W,110,"#4b956d");rect(0,220,W,140,"#3b795c")}if(!fight)return;bigEnemy(fight.foe.kind,470,65,now);if(fight.party[0].hp>0)character("hero",95,145,"right",Math.floor(now/500)%2,2);const k=fight.party.find(v=>v.id==="kumi");if(k?.hp>0)character("kumi",195,142,"right",Math.floor(now/520)%2,2);if(fight.captain){rect(75,135,215,4,"#f5d86f");rect(84,132,197,2,"#88e7f2")}rect(375,16,225,24,"#03152bd9");rect(382,25,212,9,"#151827");rect(382,25,212*fight.foe.hp/fight.foe.maxHp,9,fight.foe.boss?"#b65a8b":"#df6c73");c.fillStyle="#effcff";c.font="bold 11px sans-serif";c.fillText(fight.foe.name,384,15);for(const n of numbers){c.globalAlpha=n.life;c.fillStyle=n.color;c.font="bold 18px monospace";c.textAlign="center";c.fillText(n.text,n.x,n.y);c.globalAlpha=1}}
function bigEnemy(kind,x,y,now){const b=Math.sin(now/330)*2;if(kind==="boss"){rect(x-55,y-18+b,110,88,"#211a35");rect(x-38,y-46+b,76,60,"#382651");rect(x-31,y-64+b,15,25,"#68467a");rect(x+23,y-64+b,15,25,"#68467a");rect(x-24,y-25+b,10,9,"#fa6389");rect(x+17,y-25+b,10,9,"#fa6389");rect(x-15,y+b,30,8,"#0c0a16");rect(x-78,y+15+b,24,64,"#171324");rect(x+55,y+15+b,24,64,"#171324")}else if(kind==="hound"){rect(x-62,y+15+b,92,40,"#454c62");rect(x+12,y-5+b,45,42,"#5c647b");rect(x+18,y-24+b,15,22,"#353b51");rect(x+45,y-22+b,15,23,"#353b51");rect(x+38,y+7+b,7,7,"#fb6d82");rect(x-50,y+50+b,15,36,"#303747");rect(x+5,y+50+b,15,36,"#303747")}else if(kind==="armor"){rect(x-28,y-35+b,58,33,"#7b8d9b");rect(x-40,y-8+b,80,67,"#586a79");rect(x-18,y-17+b,39,8,"#17222d");rect(x-6,y-16+b,9,7,"#ef6478");rect(x-62,y+6+b,22,61,"#83939e");rect(x+40,y+6+b,22,61,"#83939e")}else if(kind==="bat"){rect(x-15,y+b,40,50,"#7258a9");rect(x-75,y-8+b,60,28,"#554180");rect(x+25,y-8+b,60,28,"#554180");rect(x-48,y-25+b,20,21,"#8d72bb");rect(x+45,y-25+b,20,21,"#8d72bb");rect(x-2,y+12+b,7,7,"#f07b91");rect(x+17,y+12+b,7,7,"#f07b91")}else{rect(x-40,y+b,78,60,"#54bfd6");rect(x-20,y-25+b,44,40,"#70dae8");rect(x-9,y+12+b,9,9,"#152739");rect(x+20,y+12+b,9,9,"#152739");rect(x+2,y+38+b,17,6,"#2b6475");rect(x-50,y+55+b,96,8,"#327b8f")}}
function frame(now){const dt=Math.min(40,now-last);last=now;if(mode==="map"){const held=["arrowup","w","arrowdown","s","arrowleft","a","arrowright","d"].find(k=>keys.has(k));if(held&&now-lastMove>145){const d=keyDir(held);if(d)move(d);lastMove=now}}numbers=numbers.map(n=>({...n,life:n.life-dt/850,y:n.y-dt*.026})).filter(n=>n.life>0);shake=Math.max(0,shake-dt*.04);flash=Math.max(0,flash-dt/480);if(fadeDir){fade+=fadeDir*dt/430;if(fadeDir>0&&fade>=1){fade=1;const cb=fadeCb;fadeCb=null;if(cb)cb();fadeDir=-1}else if(fadeDir<0&&fade<=0){fade=0;fadeDir=0}}c.save();if(shake)c.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);if(mode==="title"||scene==="title")renderTitle(now);else if(["room","glow","warp","meadow","ending"].includes(scene))cinematic(scene,now);else if(mode==="battle"||scene==="battle")renderBattle(now);else renderWorld(now);c.restore();if(flash){c.fillStyle=`rgba(235,253,255,${Math.min(.75,flash)})`;c.fillRect(0,0,W,H)}if(fade){c.fillStyle=`rgba(2,7,17,${fade})`;c.fillRect(0,0,W,H)}requestAnimationFrame(frame)}
window.__HQ0_TEST__={state:()=>JSON.parse(JSON.stringify(s)),settle(){fade=0;fadeDir=0;fadeCb=null},step(x){if(x==="city"){s.flags.tutorial=true;s.map="city";s.x=10;s.y=4}else if(x==="raid"){s.flags.tutorial=true;s.flags.metKumi=true;s.flags.raid=true;s.flags.kumi=true;s.map="grass";s.x=15;s.y=5}else if(x==="cave"){s.flags.tutorial=true;s.flags.metKumi=true;s.flags.raidWon=true;s.flags.kumi=true;s.flags.cave=true;s.map="cave";s.x=10;s.y=9}else if(x==="boss"){s.flags.tutorial=true;s.flags.metKumi=true;s.flags.raidWon=true;s.flags.kumi=true;s.flags.cave=true;s.map="cave";s.x=10;s.y=2;s.lv=4;s.maxHp=93;s.maxMp=27;s.atk=22;s.def=13;s.hp=heroMaxHp();s.mp=s.maxMp}fade=0;fadeDir=0;scene="map";buildEnemies();setMode("map");hud()}};
buildEnemies();bind();setMode("title");titleButtons();requestAnimationFrame(frame);
})();
